export const V5_FLAG_NAMES = Object.freeze([
  'V5_WORKSPACE',
  'V5_SYNC',
  'V5_EVALUATION',
  'V5_ANALYTICS',
  'V5_SEARCH',
  'V5_PROMPT_DETAIL',
  'V5_VARIABLES',
  'V5_PROMPT_HEALTH',
  'V5_PROMPT_EXPLAINER',
  'V5_SMART_COLLECTIONS',
  'V5_EXECUTION_ENGINE',
  'V5_IMMERSIVE_RUN',
  'V5_AI_IMPROVE',
  'V5_COST_GUARD',
  'V5_PROVIDER_SELECTOR',
  'V5_COMMAND_PALETTE',
  'V5_CLOUD_SYNC',
  'V5_USAGE_ANALYTICS',
  'V5_WORKFLOW',
  'V5_VISUAL_SYSTEM',
  'V5_MISSION_CONTROL',
  'V5_PREMIUM_CARDS',
  'V5_SHARED_PROMPT_TRANSITION',
]);

function enabled(value) {
  return typeof value === 'string' && value.trim().toLowerCase() === 'true';
}

export function readFeatureFlags(env = {}) {
  return Object.fromEntries(
    V5_FLAG_NAMES.map((name) => [name, enabled(env[`NEXT_PUBLIC_${name}`])]),
  );
}

export function isFeatureEnabled(flags, name) {
  if (!V5_FLAG_NAMES.includes(name)) return false;
  return Boolean(flags?.[name]);
}

export const V5_FEATURE_FLAGS = Object.freeze(readFeatureFlags({
  NEXT_PUBLIC_V5_WORKSPACE: process.env.NEXT_PUBLIC_V5_WORKSPACE,
  NEXT_PUBLIC_V5_SYNC: process.env.NEXT_PUBLIC_V5_SYNC,
  NEXT_PUBLIC_V5_EVALUATION: process.env.NEXT_PUBLIC_V5_EVALUATION,
  NEXT_PUBLIC_V5_ANALYTICS: process.env.NEXT_PUBLIC_V5_ANALYTICS,
  NEXT_PUBLIC_V5_SEARCH: process.env.NEXT_PUBLIC_V5_SEARCH,
  NEXT_PUBLIC_V5_PROMPT_DETAIL: process.env.NEXT_PUBLIC_V5_PROMPT_DETAIL,
  NEXT_PUBLIC_V5_VARIABLES: process.env.NEXT_PUBLIC_V5_VARIABLES,
  NEXT_PUBLIC_V5_PROMPT_HEALTH: process.env.NEXT_PUBLIC_V5_PROMPT_HEALTH,
  NEXT_PUBLIC_V5_PROMPT_EXPLAINER: process.env.NEXT_PUBLIC_V5_PROMPT_EXPLAINER,
  NEXT_PUBLIC_V5_SMART_COLLECTIONS: process.env.NEXT_PUBLIC_V5_SMART_COLLECTIONS,
  NEXT_PUBLIC_V5_EXECUTION_ENGINE: process.env.NEXT_PUBLIC_V5_EXECUTION_ENGINE,
  NEXT_PUBLIC_V5_IMMERSIVE_RUN: process.env.NEXT_PUBLIC_V5_IMMERSIVE_RUN,
  NEXT_PUBLIC_V5_AI_IMPROVE: process.env.NEXT_PUBLIC_V5_AI_IMPROVE,
  NEXT_PUBLIC_V5_COST_GUARD: process.env.NEXT_PUBLIC_V5_COST_GUARD,
  NEXT_PUBLIC_V5_PROVIDER_SELECTOR: process.env.NEXT_PUBLIC_V5_PROVIDER_SELECTOR,
  NEXT_PUBLIC_V5_COMMAND_PALETTE: process.env.NEXT_PUBLIC_V5_COMMAND_PALETTE,
  NEXT_PUBLIC_V5_CLOUD_SYNC: process.env.NEXT_PUBLIC_V5_CLOUD_SYNC,
  NEXT_PUBLIC_V5_USAGE_ANALYTICS: process.env.NEXT_PUBLIC_V5_USAGE_ANALYTICS,
  NEXT_PUBLIC_V5_WORKFLOW: process.env.NEXT_PUBLIC_V5_WORKFLOW,
  NEXT_PUBLIC_V5_VISUAL_SYSTEM: process.env.NEXT_PUBLIC_V5_VISUAL_SYSTEM,
  NEXT_PUBLIC_V5_MISSION_CONTROL: process.env.NEXT_PUBLIC_V5_MISSION_CONTROL,
  NEXT_PUBLIC_V5_PREMIUM_CARDS: process.env.NEXT_PUBLIC_V5_PREMIUM_CARDS,
  NEXT_PUBLIC_V5_SHARED_PROMPT_TRANSITION: process.env.NEXT_PUBLIC_V5_SHARED_PROMPT_TRANSITION,
}));
