function meta(purposeTh, useCasesTh, expectedOutputTh, exampleInputTh, inputGuideTh = {}) {
  return Object.freeze({ purposeTh, useCasesTh, expectedOutputTh, exampleInputTh, inputGuideTh });
}

export const CORE_PROMPT_QUALITY_V2_METADATA = Object.freeze({
  DEEP_RESEARCH_ASSISTANT: meta(
    'ช่วยวางกรอบและสังเคราะห์งานวิจัยจากหัวข้อที่กำหนด โดยแยกข้อเท็จจริง การตีความ และข้อมูลที่ยังไม่แน่นอนออกจากกันอย่างชัดเจน',
    ['วิจัยหัวข้อใหม่อย่างเป็นระบบ', 'เตรียม brief ก่อนตัดสินใจ', 'ตรวจมุมมองที่ขัดแย้งกัน'],
    ['ข้อเท็จจริงและแนวคิดสำคัญ', 'หลักฐานและข้อโต้แย้ง', 'ข้อจำกัด ความไม่แน่นอน และคำถามที่ยังเปิดอยู่'],
    'หัวข้อ: Zero Trust Network\nวัตถุประสงค์: เปรียบเทียบแนวทางใช้งานในองค์กรขนาดกลางและความเสี่ยงที่ต้องตรวจสอบ',
  ),
  FACT_CHECKER: meta(
    'ช่วยตรวจข้อกล่าวอ้างจากหลักฐานที่ผู้ใช้มี โดยไม่ถือว่าข้อความที่ไม่มีแหล่งรองรับเป็นข้อเท็จจริง และระบุความไม่แน่นอนเมื่อหลักฐานยังไม่พอ',
    ['ตรวจข่าวหรือข้อความอ้างอิง', 'ตรวจ claim ก่อนเผยแพร่', 'หาบริบทที่ขาดหาย'],
    ['Verdict', 'หลักฐานสนับสนุนและคัดค้าน', 'บริบทที่ขาดและระดับความมั่นใจ'],
    'Claim: บริษัท A มีรายได้โต 50% ในไตรมาสล่าสุด พร้อมแนบแหล่งข้อมูลที่มีให้ตรวจ',
  ),
  ARTICLE_ANALYZER: meta(
    'ช่วยอ่านบทความเชิงวิพากษ์ เพื่อแยกประเด็นหลัก หลักฐาน สมมติฐาน อคติ และข้อมูลที่ควรตรวจเพิ่มก่อนเชื่อข้อสรุป',
    ['วิเคราะห์บทความข่าว', 'ทบทวนบทความเชิงความคิดเห็น', 'สรุปประเด็นก่อนประชุม'],
    ['ประเด็นหลักและ key points', 'หลักฐาน/สมมติฐาน/อคติ', 'ข้อมูลที่ขาดและคำถามที่ควรตรวจต่อ'],
    'วางบทความฉบับเต็มที่ต้องการวิเคราะห์ โดยคงหัวข้อ ตัวเลข และข้อความอ้างอิงสำคัญไว้',
  ),
  PAPER_ANALYZER: meta(
    'ช่วยถอดโครงสร้างงานวิจัย ตั้งแต่คำถามวิจัย วิธีการ ชุดข้อมูล ผลลัพธ์ ไปจนถึงข้อจำกัด พร้อมอธิบายเป็นภาษาที่คนทั่วไปเข้าใจได้',
    ['อ่าน paper ก่อนทำ literature review', 'ตรวจ methodology และ limitations', 'สรุป paper ให้ทีมที่ไม่ใช่นักวิจัย'],
    ['Research question และ methodology', 'Dataset/ผลการศึกษา/สถิติ', 'ข้อจำกัด อคติ และคำอธิบายแบบง่าย'],
    'แนบ abstract, methodology, results และ conclusion ของ paper ที่ต้องการวิเคราะห์',
  ),
  SOURCE_COMPARATOR: meta(
    'ช่วยเปรียบเทียบหลายแหล่งข้อมูลในหัวข้อเดียวกัน เพื่อดูว่าจุดใดตรงกัน ขัดแย้งกัน หรือยังไม่มีหลักฐานเพียงพอ โดยไม่ใช้จำนวนแหล่งที่พูดซ้ำเป็นหลักฐานแทนคุณภาพ',
    ['เทียบข่าวหลายสำนัก', 'ตรวจแหล่งอ้างอิงก่อนทำรายงาน', 'หา disagreement ระหว่างแหล่งข้อมูล'],
    ['ตาราง/รายงานเปรียบเทียบ claim', 'จุดที่เห็นตรงกันและขัดแย้ง', 'ตัวบ่งชี้ความน่าเชื่อถือและข้อมูลที่ขาด'],
    'หัวข้อ: ผลกระทบของนโยบาย X\nแหล่งข้อมูล: Source A..., Source B..., Source C...',
  ),
  CODE_REVIEWER: meta(
    'ช่วยตรวจ source code แบบเป็นระบบ ทั้ง correctness, security, performance, architecture และ maintainability พร้อมชี้ตำแหน่งและแนวแก้ที่นำไปใช้ต่อได้',
    ['Review ก่อน merge', 'ตรวจโค้ดที่มี bug/risk', 'หา technical debt ที่สำคัญ'],
    ['รายการปัญหาพร้อม severity และตำแหน่ง', 'เหตุผลและผลกระทบ', 'แนวแก้และตัวอย่างโค้ดที่ปรับปรุง'],
    'Technology: Next.js / React\nCode: วาง component หรือ module ที่ต้องการ review',
  ),
  BUG_HUNTER: meta(
    'ช่วยไล่ root cause ของ bug จาก expected behavior, actual behavior, error และ code โดยแยกสาเหตุที่มีหลักฐานออกจากสมมติฐาน',
    ['Debug error ที่ทำซ้ำได้', 'หา regression หลังเปลี่ยนโค้ด', 'วาง diagnostic steps ก่อนแก้'],
    ['สาเหตุที่เป็นไปได้เรียงตามหลักฐาน', 'ขั้นตอน reproduce/diagnose', 'แนวแก้และวิธี verify regression'],
    'Expected: กด Save แล้วอยู่หน้าเดิม\nActual: เด้งไปหน้าอื่น\nError: ...\nCode: ...',
  ),
  UNIT_TEST_GENERATOR: meta(
    'ช่วยสร้าง Unit Test จากโค้ดและ testing framework ที่กำหนด ครอบคลุมกรณีปกติ edge case invalid input และ regression โดยอธิบายสิ่งที่แต่ละ test พิสูจน์',
    ['เพิ่ม coverage ให้ module สำคัญ', 'สร้าง regression test ก่อนแก้ bug', 'เตรียม test cases สำหรับ refactor'],
    ['ชุด Unit Test ที่รันได้', 'normal/edge/failure/regression cases', 'คำอธิบายเป้าหมายของแต่ละ test'],
    'Code: ฟังก์ชัน validateOrder(...)\nTesting framework: node:test',
  ),
  CODE_OPTIMIZER: meta(
    'ช่วยวิเคราะห์โค้ดเพื่อหา bottleneck และการทำงานซ้ำก่อนเสนอ optimization โดยต้องอธิบาย trade-off และไม่เปลี่ยน behavior โดยไม่มีเหตุผล',
    ['ลดเวลาประมวลผล', 'ลด memory/network/database work', 'ปรับโค้ดให้ดูแลง่ายขึ้น'],
    ['จุดที่ควร optimize พร้อมเหตุผล', 'ผลกระทบและ trade-off', 'โค้ดเวอร์ชันที่ปรับแล้ว'],
    'Optimization goal: ลด API calls ซ้ำ\nCode: วางโค้ดที่ต้องการวิเคราะห์',
  ),
  TIME_COMPLEXITY_ANALYZER: meta(
    'ช่วยอธิบาย Time/Space Complexity ของโค้ด พร้อมระบุ operation ที่เป็นตัวกำหนด Big-O และเสนอ algorithm ที่ดีกว่าเมื่อมีทางเลือก',
    ['ทบทวน algorithm', 'เตรียมสัมภาษณ์ coding', 'ตรวจ scalability ก่อนใช้กับข้อมูลขนาดใหญ่'],
    ['Time/Space complexity', 'Best/Average/Worst case', 'จุดที่สร้าง complexity และทางเลือกที่มีประสิทธิภาพกว่า'],
    'Code: วาง loop/algorithm ที่ต้องการวิเคราะห์ เช่น nested loops สำหรับค้นหารายการซ้ำ',
  ),
  REGEX_GENERATOR: meta(
    'ช่วยแปลง requirement เป็น Regular Expression พร้อมตัวอย่าง valid/invalid และรูปแบบ escaped สำหรับภาษาที่ใช้ เพื่อลด regex ที่กว้างเกินความต้องการ',
    ['สร้าง input validation', 'จับรูปแบบ log/text', 'สร้าง regex สำหรับภาษาโปรแกรมเฉพาะ'],
    ['Regex', 'คำอธิบาย pattern', 'valid/invalid examples และ edge cases'],
    'Requirement: รับรหัสรูปแบบ ABC-1234 เท่านั้น\nLanguage: JavaScript',
  ),
  DOCKER_GENERATOR: meta(
    'ช่วยออกแบบ Docker setup สำหรับ production จาก application, technology และ requirements โดยคำนึงถึง security, caching, image size และ health check',
    ['Containerize web app', 'เตรียม Dockerfile สำหรับ production', 'เพิ่ม compose สำหรับ dependency ที่จำเป็น'],
    ['Dockerfile และ .dockerignore', 'compose/config ที่จำเป็น', 'build/run/health-check instructions'],
    'Application: Next.js web app\nTechnology: Node.js 22\nRequirements: non-root user, health check, production build',
  ),
  API_DESIGNER: meta(
    'ช่วยออกแบบ REST API จาก requirements ให้ครบ resource, endpoint, schema, auth, validation, error, pagination และ versioning พร้อมตัวอย่าง request/response',
    ['ออกแบบ backend API ใหม่', 'ทำ API contract ก่อนลงมือเขียนโค้ด', 'ทบทวน coverage ของ endpoint'],
    ['รายการ resource/endpoint', 'request/response schemas', 'auth/validation/error/rate-limit/versioning guidance'],
    'Application: ระบบ Ticket\nRequirements: สร้าง ticket, assign, comment, close และค้นหาตามสถานะ',
  ),
  DATABASE_SCHEMA_DESIGNER: meta(
    'ช่วยออกแบบ relational schema จากระบบและ requirements พร้อมอธิบาย relationship, normalization, indexes, constraints และสร้าง SQL CREATE TABLE เป็นจุดเริ่มต้น',
    ['ออกแบบ schema ระบบใหม่', 'แปลง requirements เป็นตาราง', 'ทบทวน key/index/constraint ก่อนพัฒนา'],
    ['Entities/Tables/Columns', 'Keys/Relationships/Indexes/Constraints', 'SQL CREATE TABLE และเหตุผลด้าน normalization'],
    'System: ระบบจัดการออเดอร์\nRequirements: ลูกค้า สินค้า ออเดอร์ รายการสินค้า การชำระเงิน และสถานะ',
  ),
  JSON_EXTRACTOR: meta(
    'ช่วยดึงข้อมูลจากเนื้อหาที่ไม่มีโครงสร้างให้ตรง schema ที่กำหนด และคืน valid JSON โดยใช้ null เมื่อไม่มีข้อมูลแทนการเดา',
    ['แปลงข้อความเป็น JSON', 'เตรียมข้อมูลเข้า API', 'ดึง field จากเอกสารตาม schema'],
    ['Valid JSON ตาม schema', 'ค่าที่รักษาตัวเลข/ชื่อ/วันที่จากต้นฉบับ', 'null สำหรับข้อมูลที่ระบุไม่ได้'],
    'Content: Order #A-102, customer Somchai, total 1,250 THB\nSchema: {"order_id":"","customer":"","total":0}',
  ),
  TABLE_EXTRACTOR: meta(
    'ช่วยแปลงเนื้อหาที่กระจัดกระจายเป็นตารางตาม columns ที่ผู้ใช้กำหนด โดยรักษาค่าต้นฉบับ ลบ duplicate และไม่เดาข้อมูลที่หาย',
    ['ดึงรายการจากข้อความยาว', 'เตรียมข้อมูลสำหรับ spreadsheet', 'จัดข้อมูลหลาย entity ให้หนึ่งแถวต่อรายการ'],
    ['ตารางตาม columns ที่ระบุ', 'ข้อมูลหนึ่ง entity ต่อแถว', 'N/A สำหรับค่าที่ไม่มีและไม่มี duplicate'],
    'Content: รายการอุปกรณ์หลายบรรทัด...\nColumns: Device, IP, Status, Owner',
  ),
  SENTIMENT_ANALYZER: meta(
    'ช่วยวิเคราะห์ sentiment, emotion, intent และ urgency จากข้อความ โดยอธิบายสัญญาณที่ใช้ประกอบการจัดประเภทแทนการคืนคะแนนอย่างเดียว',
    ['วิเคราะห์ feedback ลูกค้า', 'คัดแยกข้อความเร่งด่วน', 'ดูแนวโน้มอารมณ์และ intent'],
    ['Overall sentiment และ scores', 'emotional signals/phrases', 'intent, urgency และข้อสังเกตเรื่อง sarcasm'],
    'Text: “ระบบล่มอีกแล้ว ต้องใช้ก่อนบ่ายนี้ ช่วยแก้ด่วน”',
  ),
  DATA_CLASSIFIER: meta(
    'ช่วยจำแนก input ให้เป็นหนึ่งในหมวดที่ผู้ใช้กำหนด และคืน JSON พร้อม confidence/reason โดยห้ามสร้างหมวดใหม่เอง',
    ['จัดประเภท ticket', 'จำแนกข้อความตาม taxonomy', 'เตรียม label สำหรับ workflow'],
    ['JSON ที่มี category/confidence/reason', 'alternative category เมื่อเหมาะสม', 'ใช้เฉพาะ categories ที่กำหนด'],
    'Input: “VPN ต่อไม่ได้หลังเปลี่ยนรหัสผ่าน”\nCategories: Network, Account, Application, Hardware',
  ),
  IMAGE_OBJECT_ANALYZER: meta(
    'ช่วยอธิบายสิ่งที่มองเห็นในภาพ เช่น วัตถุ คน สภาพแวดล้อม ข้อความ สี และรายละเอียดสำคัญ โดยแยก observation ออกจาก interpretation ที่ไม่แน่นอน',
    ['ตรวจรายละเอียดในภาพ', 'สรุปองค์ประกอบของภาพ', 'อ่านข้อความและวัตถุที่มองเห็น'],
    ['รายการสิ่งที่สังเกตเห็น', 'ข้อความ/สี/วัสดุ/สภาพแวดล้อม', 'ส่วนที่เป็นการตีความหรือยังไม่แน่นอน'],
    'แนบภาพที่ต้องการวิเคราะห์ เช่น ภาพหน้าจออุปกรณ์หรือสถานที่ แล้วกด Run',
  ),
  IMAGE_TO_JSON: meta(
    'ช่วยดึงข้อมูลที่มองเห็นในภาพให้อยู่ใน JSON ตาม schema ที่กำหนด โดยใช้ null เมื่ออ่านหรือระบุค่าไม่ได้และไม่แต่งข้อมูลเพิ่ม',
    ['ดึงข้อมูลจาก screenshot', 'แปลงข้อมูลบนภาพเป็น structured data', 'อ่าน field จากเอกสารภาพตาม schema'],
    ['Valid JSON ตาม schema', 'ข้อความที่ถอดจากภาพอย่างระมัดระวัง', 'null สำหรับค่าที่ระบุไม่ได้'],
    'แนบภาพใบงาน\nSchema: {"ticket_id":"","status":"","assignee":""}',
  ),
  VIDEO_QA: meta(
    'ช่วยตอบคำถามจากวิดีโอโดยอ้างอิงสิ่งที่สังเกตเห็นและ timestamp ที่เกี่ยวข้อง พร้อมระบุความมั่นใจและรายละเอียดที่ไม่แน่นอน',
    ['ถามเหตุการณ์ในวิดีโอ', 'หา timestamp ของช่วงสำคัญ', 'สรุปหลักฐานจากภาพเคลื่อนไหว'],
    ['คำตอบตรงคำถาม', 'timestamp และ observed evidence', 'confidence และ uncertain details'],
    'แนบวิดีโอ\nQuestion: ช่วงไหนที่อุปกรณ์เริ่มแสดงไฟเตือนสีแดง?',
  ),
  AUDIO_TRANSCRIBER: meta(
    'ช่วยถอดเสียงจากไฟล์ audio พร้อมแยกผู้พูด ใส่ timestamp และทำเครื่องหมายช่วงที่ฟังไม่ชัดโดยไม่เดาคำที่ไม่ได้ยิน',
    ['ถอดประชุม', 'ถอดสัมภาษณ์', 'สร้าง transcript ที่ค้นตามเวลาได้'],
    ['Transcript แยกผู้พูด', 'timestamps', 'ตำแหน่งเสียงไม่ชัดและคำศัพท์สำคัญที่รักษาไว้'],
    'แนบไฟล์เสียงการประชุมที่ต้องการถอด แล้วกด Run',
  ),
  BLOG_GENERATOR: meta(
    'ช่วยสร้างบทความแบบยาวจาก topic, audience และ tone โดยจัดโครงสร้างให้อ่านง่ายและยึดข้อมูลที่ผู้ใช้ให้ ไม่เติมข้อเท็จจริงเฉพาะที่ไม่มีแหล่งรองรับ',
    ['ร่างบทความความรู้', 'สร้าง first draft สำหรับบล็อก', 'ปรับเนื้อหาให้ตรงกลุ่มเป้าหมาย'],
    ['หัวข้อและโครงสร้างบทความ', 'เนื้อหาตาม audience/tone', 'สรุปหรือ CTA ตามโจทย์'],
    'Topic: วิธีเริ่มต้นทำ Network Monitoring\nAudience: IT Support มือใหม่\nTone: Professional but simple',
  ),
  SEO_CONTENT_WRITER: meta(
    'ช่วยร่างบทความที่มีโครงสร้างเหมาะกับ SEO จาก keyword และ search intent พร้อม metadata/FAQ โดยไม่ยัด keyword จนเสียความอ่านง่าย',
    ['สร้าง SEO article draft', 'วาง heading ตาม search intent', 'เตรียม meta title/description และ FAQ'],
    ['SEO article structure', 'metadata', 'FAQ และการใช้ keyword อย่างเป็นธรรมชาติ'],
    'Keyword: network monitoring tools\nSearch intent: เปรียบเทียบเครื่องมือสำหรับทีม IT ขนาดเล็ก',
  ),
  SOCIAL_CONTENT_GENERATOR: meta(
    'ช่วยสร้าง social content ตาม platform, topic และ tone พร้อมปรับความยาว/รูปแบบให้เหมาะกับช่องทาง โดยไม่แต่ง claim ที่ผู้ใช้ไม่ได้ให้มา',
    ['ร่างโพสต์ประชาสัมพันธ์', 'แปลงหัวข้อเป็น social copy', 'สร้างหลายมุมสำหรับ campaign'],
    ['โพสต์พร้อมใช้ตาม platform', 'hook/body/CTA ที่เหมาะสม', 'ตัวเลือกข้อความเมื่อ prompt ขอหลายแบบ'],
    'Platform: LinkedIn\nTopic: เปิดตัว dashboard ใหม่ของทีม IT\nTone: Professional',
  ),
  MEETING_SUMMARIZER: meta(
    'ช่วยสรุป transcript การประชุมให้เหลือประเด็นสำคัญ การตัดสินใจ ประเด็นค้าง และสิ่งที่ต้องติดตาม โดยไม่สร้าง owner/deadline ที่ไม่ได้พูดไว้',
    ['สรุปประชุมทีม', 'ทบทวน decision หลัง call', 'ทำ meeting recap'],
    ['Summary', 'decisions/key points', 'open questions และ follow-up ที่พบใน transcript'],
    'Transcript: วางข้อความถอดเสียงการประชุมทั้งหมด โดยคงชื่อผู้พูดและเวลาหากมี',
  ),
  ACTION_ITEM_EXTRACTOR: meta(
    'ช่วยดึง action item ที่ระบุอยู่ในข้อความหรือ transcript พร้อม owner/deadline เฉพาะเมื่อมีข้อมูลจริง และแยกสิ่งที่ยังไม่ระบุออกจากกัน',
    ['ดึงงานจาก meeting notes', 'ทำ task list จาก transcript', 'ตรวจงานที่ยังไม่มี owner/deadline'],
    ['Action items', 'owner/deadline เมื่อถูกระบุ', 'รายการที่ข้อมูลผู้รับผิดชอบหรือกำหนดเวลายังขาด'],
    'Content: “Mek ตรวจ log ภายในวันศุกร์ ส่วนทีม Network จะยืนยัน VLAN แต่ยังไม่กำหนดวัน”',
  ),
  PRESENTATION_BUILDER: meta(
    'ช่วยวางโครง presentation จาก topic, audience และจำนวนสไลด์ โดยกำหนดหน้าที่ของแต่ละสไลด์และ key message ก่อนนำไปออกแบบจริง',
    ['สร้าง slide outline', 'จัดลำดับเรื่องสำหรับผู้บริหาร', 'แปลงหัวข้อยาวเป็น presentation'],
    ['โครงสไลด์ตามจำนวนที่กำหนด', 'หัวข้อและ key message ต่อสไลด์', 'ข้อเสนอสำหรับข้อมูล/visual ที่ควรใส่'],
    'Topic: Quarterly IT Operations Review\nAudience: Management\nSlides: 8',
  ),
  PERSONAL_TUTOR: meta(
    'ช่วยสอนหัวข้อจากระดับของผู้เรียน โดยอธิบายทีละขั้น ใช้ตัวอย่าง และตรวจความเข้าใจ แทนการให้คำตอบยาวโดยไม่ประเมินพื้นฐาน',
    ['เรียน technical concept ใหม่', 'ทบทวนก่อนสอบ', 'ขอแบบฝึกหัดตามระดับ'],
    ['คำอธิบายตามระดับ', 'ตัวอย่างและแบบฝึกหัด', 'คำถามตรวจความเข้าใจและหัวข้อที่ควรเรียนต่อ'],
    'Topic: OSPF\nLevel: Beginner\nGoal: เข้าใจ neighbor adjacency และเลือก DR/BDR',
  ),
  QUIZ_GENERATOR: meta(
    'ช่วยสร้างแบบทดสอบจาก topic, level และจำนวนข้อ พร้อมเฉลย/คำอธิบายที่ใช้ตรวจความเข้าใจจริง ไม่ใช่เพียงจำคำศัพท์',
    ['สร้าง quiz ทบทวนบทเรียน', 'เตรียมข้อสอบฝึกทำ', 'ตรวจจุดอ่อนหลังเรียน'],
    ['ชุดคำถามตามจำนวนและระดับ', 'เฉลย', 'คำอธิบายเหตุผลของคำตอบ'],
    'Topic: VLAN และ Trunk\nLevel: Intermediate\nCount: 10',
  ),
});
