function freezeMeta(value) {
  return Object.freeze({
    ...value,
    useCasesTh: Object.freeze([...(value.useCasesTh || [])]),
    inputGuideTh: Object.freeze({ ...(value.inputGuideTh || {}) }),
    expectedOutputTh: Object.freeze([...(value.expectedOutputTh || [])]),
  });
}

export const CORE_QUALITY_METADATA = Object.freeze({
  DEEP_RESEARCH_ASSISTANT: freezeMeta({
    descriptionTh: 'วิจัยหัวข้ออย่างเป็นระบบ พร้อมหลักฐาน มุมมองที่แตกต่าง ข้อจำกัด และความไม่แน่นอน',
    purposeTh: 'ใช้วางกรอบการวิจัยเชิงลึกจากหัวข้อและเป้าหมายที่ระบุ โดยแยกข้อเท็จจริง การตีความ และประเด็นที่ยังไม่แน่นอนอย่างชัดเจน',
    useCasesTh: ['เตรียมรายงานวิจัย', 'สำรวจประเด็นก่อนตัดสินใจ', 'ตรวจช่องว่างและข้อจำกัดของหลักฐาน'],
    inputGuideTh: { topic: 'ระบุหัวข้อให้เฉพาะเจาะจง', objectives: 'ระบุคำถามหรือเป้าหมายที่ต้องการหาคำตอบ' },
    expectedOutputTh: ['ข้อเท็จจริงและแนวคิดสำคัญ', 'หลักฐานและมุมมองที่ขัดแย้ง', 'ข้อจำกัด ความไม่แน่นอน และแหล่งที่ควรตรวจต่อ'],
    exampleInputTh: 'หัวข้อ: ผลกระทบของ Wi-Fi 6E ต่อเครือข่ายองค์กร\nเป้าหมาย: เปรียบเทียบประสิทธิภาพ ความเสี่ยง และข้อจำกัดก่อนอัปเกรด',
  }),
  FACT_CHECKER: freezeMeta({
    descriptionTh: 'วิเคราะห์ข้อกล่าวอ้าง หลักฐาน บริบทที่ขาดหาย และความไม่แน่นอน',
    purposeTh: 'ใช้ตรวจข้อกล่าวอ้างจากข้อมูลที่มี โดยไม่ถือว่าข้อความที่ยังไม่มีหลักฐานเป็นข้อเท็จจริง และชี้สิ่งที่ควรตรวจยืนยันต่อ',
    useCasesTh: ['ตรวจข่าวหรือข้อความอ้างอิง', 'ตรวจ claim ในรายงาน', 'แยกข้อเท็จจริงออกจากข้อสรุป'],
    inputGuideTh: { claim: 'วางข้อกล่าวอ้างเต็มประโยค พร้อมตัวเลขหรือเงื่อนไขสำคัญถ้ามี' },
    expectedOutputTh: ['Verdict พร้อมเหตุผล', 'หลักฐานสนับสนุน/ขัดแย้ง', 'บริบทที่ขาดและระดับความมั่นใจ'],
    exampleInputTh: 'Claim: “Wi-Fi 6E ทำให้ latency ต่ำกว่า Wi-Fi 6 เสมอในทุกสภาพแวดล้อม”',
  }),
  ARTICLE_ANALYZER: freezeMeta({
    descriptionTh: 'วิเคราะห์ข้อโต้แย้ง หลักฐาน สมมติฐาน อคติ และข้อมูลที่ขาดหายของบทความ',
    purposeTh: 'ใช้แยกโครงสร้างเหตุผลของบทความออกเป็นประเด็นหลัก หลักฐาน สมมติฐาน จุดอ่อน และคำถามที่ควรตรวจต่อ',
    useCasesTh: ['อ่านบทความยาวอย่างเป็นระบบ', 'เตรียมวิจารณ์บทความ', 'ตรวจ bias และข้อมูลที่ขาด'],
    inputGuideTh: { article: 'วางบทความหรือส่วนที่ต้องการวิเคราะห์ให้ครบที่สุด' },
    expectedOutputTh: ['ประเด็นและข้อโต้แย้งหลัก', 'หลักฐาน/สมมติฐาน/อคติ', 'ข้อมูลที่ขาดและคำถามติดตาม'],
    exampleInputTh: 'บทความ: เนื้อหาเกี่ยวกับการนำ AI มาใช้ในงาน Helpdesk พร้อมข้ออ้างเรื่อง productivity ...',
  }),
  PAPER_ANALYZER: freezeMeta({
    descriptionTh: 'วิเคราะห์งานวิชาการ ระเบียบวิธี ข้อมูล ผลการศึกษา และข้อจำกัด',
    purposeTh: 'ใช้แตกงานวิจัยเป็นคำถาม วิธีการ ข้อมูล ผลลัพธ์ ข้อจำกัด และผลเชิงปฏิบัติ พร้อมสรุปภาษาง่ายสำหรับคนที่ไม่ใช่ผู้เชี่ยวชาญ',
    useCasesTh: ['อ่าน paper ก่อนทำ literature review', 'ตรวจ methodology และ limitation', 'สรุป paper ให้ทีมที่ไม่ใช่นักวิจัย'],
    inputGuideTh: { paper: 'วาง paper, abstract หรือข้อความจากงานวิจัยที่ต้องการวิเคราะห์' },
    expectedOutputTh: ['Research question และ methodology', 'Key findings และ limitations', 'คำอธิบายภาษาง่าย'],
    exampleInputTh: 'Paper: Abstract และ Methods ของงานวิจัยเรื่อง LLM-assisted network operations ...',
  }),
  SOURCE_COMPARATOR: freezeMeta({
    descriptionTh: 'เปรียบเทียบหลายแหล่งข้อมูล พร้อมหาจุดที่ตรงกัน ขัดแย้งกัน และสัญญาณความน่าเชื่อถือ',
    purposeTh: 'ใช้เทียบแหล่งข้อมูลหลายชุดในหัวข้อเดียวกัน โดยไม่ตีความว่าการกล่าวซ้ำเท่ากับหลักฐานอิสระ',
    useCasesTh: ['เทียบข่าวหลายสำนัก', 'ตรวจข้อมูลก่อนทำรายงาน', 'หาความขัดแย้งระหว่างแหล่งอ้างอิง'],
    inputGuideTh: { topic: 'ระบุหัวข้อที่ใช้เป็นแกนเปรียบเทียบ', sources: 'วางข้อความ ลิงก์ หรือรายละเอียดของแต่ละแหล่งให้แยกกันชัดเจน' },
    expectedOutputTh: ['ตารางเปรียบเทียบ claim/evidence', 'จุดที่ตรงกันและขัดแย้ง', 'สัญญาณความน่าเชื่อถือและข้อมูลที่ยังขาด'],
    exampleInputTh: 'หัวข้อ: ค่าใช้จ่าย Dynamic Maps\nSources: เอกสารผู้ให้บริการ A ...\nรีวิว B ...',
  }),
  CODE_REVIEWER: freezeMeta({
    descriptionTh: 'ตรวจโค้ดเพื่อหาบั๊ก ความเสี่ยงด้านความปลอดภัย ประสิทธิภาพ สถาปัตยกรรม และความง่ายต่อการดูแล',
    purposeTh: 'ใช้ตรวจ source code แบบเป็นรายการ issue พร้อม severity ตำแหน่ง ผลกระทบ และแนวทางแก้ โดยยังคง requirement ของระบบเดิม',
    useCasesTh: ['Review ก่อน merge', 'ตรวจ security/performance risk', 'หาจุดที่ทำให้โค้ดดูแลยาก'],
    inputGuideTh: { technology: 'ระบุภาษา Framework และ runtime ที่เกี่ยวข้อง', code: 'วางโค้ดส่วนที่ต้องการ review พร้อม context ที่จำเป็น' },
    expectedOutputTh: ['รายการ issue พร้อม severity', 'เหตุผลและแนวทางแก้', 'โค้ดปรับปรุงเมื่อข้อมูลเพียงพอ'],
    exampleInputTh: 'Technology: Next.js 16 / React 19\nCode: async function createPayment(...) { ... }',
  }),
  BUG_HUNTER: freezeMeta({
    descriptionTh: 'วิเคราะห์บั๊กของซอฟต์แวร์และหาสาเหตุราก',
    purposeTh: 'ใช้ไล่ root cause จาก expected/actual behavior, error และ code โดยแยกสาเหตุที่มีหลักฐานรองรับออกจากสมมติฐาน',
    useCasesTh: ['Bug หลัง deploy', 'ฟังก์ชันทำงานไม่ตรง requirement', 'Error ที่เกิดเฉพาะบาง input'],
    inputGuideTh: { expected_behavior: 'อธิบายสิ่งที่ควรเกิด', actual_behavior: 'อธิบายสิ่งที่เกิดจริง', error: 'วาง error/stack trace แบบไม่ตัดบรรทัดสำคัญ', code: 'วางโค้ดที่เกี่ยวข้องกับจุดเกิดปัญหา' },
    expectedOutputTh: ['Root cause candidates', 'ขั้นตอน reproduce/diagnose', 'แนวทางแก้และวิธี verify'],
    exampleInputTh: 'Expected: Save อยู่หน้าเดิม\nActual: Save แล้วเด้งหน้าอื่น\nError: ...\nCode: ...',
  }),
  UNIT_TEST_GENERATOR: freezeMeta({
    descriptionTh: 'สร้าง Unit Test ครอบคลุมกรณีปกติ ขอบเขต ข้อผิดพลาด และการถดถอย',
    purposeTh: 'ใช้สร้าง test cases จากโค้ดจริงและ testing framework ที่กำหนด โดยครอบคลุม normal, edge, invalid และ regression scenarios',
    useCasesTh: ['เพิ่ม test ให้ feature ใหม่', 'สร้าง regression test หลังแก้ bug', 'ตรวจ edge cases ที่ยังไม่มี coverage'],
    inputGuideTh: { code: 'วางฟังก์ชันหรือโมดูลที่ต้องการทดสอบ', test_framework: 'ระบุ framework และรูปแบบ test เช่น node:test, Jest, Vitest' },
    expectedOutputTh: ['ชุด Unit Test ที่รันได้', 'คำอธิบายว่าแต่ละ test ป้องกันอะไร', 'กรณี edge/failure/regression'],
    exampleInputTh: 'Code: function normalizePortState(...) { ... }\nTest framework: node:test',
  }),
  CODE_OPTIMIZER: freezeMeta({
    descriptionTh: 'ปรับโค้ดให้มีประสิทธิภาพ ใช้ทรัพยากรดี และดูแลต่อได้ง่าย',
    purposeTh: 'ใช้วิเคราะห์คอขวดและ duplication จากโค้ดที่ให้มา แล้วเสนอการปรับที่สอดคล้องกับ optimization goal โดยอธิบาย trade-off ก่อนเปลี่ยน',
    useCasesTh: ['ลดเวลาประมวลผล', 'ลด query/network ที่ซ้ำ', 'ปรับโค้ดให้อ่านและดูแลง่ายขึ้น'],
    inputGuideTh: { code: 'วางโค้ดส่วนที่ต้องการ optimize', optimization_goal: 'ระบุเป้าหมาย เช่น latency, memory, DB queries หรือ maintainability' },
    expectedOutputTh: ['จุดที่เป็น bottleneck', 'เหตุผลและ trade-off', 'ตัวอย่างโค้ดที่ปรับปรุง'],
    exampleInputTh: 'Optimization goal: ลด API calls ซ้ำและลดเวลา render\nCode: ...',
  }),
  TIME_COMPLEXITY_ANALYZER: freezeMeta({
    descriptionTh: 'วิเคราะห์ความซับซ้อนด้านเวลาและหน่วยความจำแบบ Big-O',
    purposeTh: 'ใช้วิเคราะห์ operation ที่เป็นตัวกำหนด Time/Space Complexity และเสนอ algorithm ที่ดีกว่าเมื่อมีทางเลือกที่สมเหตุสมผล',
    useCasesTh: ['ตรวจ algorithm ก่อนใช้กับข้อมูลใหญ่', 'เปรียบเทียบ implementation', 'เตรียมอธิบาย complexity ใน code review'],
    inputGuideTh: { code: 'วางโค้ดหรือ pseudocode ที่ต้องการวิเคราะห์' },
    expectedOutputTh: ['Time/Space Complexity', 'Best/Average/Worst case', 'จุดที่ทำให้ complexity สูงและทางเลือก'],
    exampleInputTh: 'Code: nested loop ที่ค้นหา duplicate ใน array ...',
  }),
  REGEX_GENERATOR: freezeMeta({
    descriptionTh: 'แปลงความต้องการภาษาธรรมชาติเป็น Regular Expression',
    purposeTh: 'ใช้สร้าง Regex จาก requirement ที่ชัดเจน พร้อมตัวอย่างผ่าน/ไม่ผ่าน edge cases และรูปแบบ escaped สำหรับภาษาที่เลือก',
    useCasesTh: ['Validate input', 'ดึง pattern จากข้อความ', 'สร้าง Regex สำหรับ code/config'],
    inputGuideTh: { requirement: 'อธิบายรูปแบบที่ต้อง match และสิ่งที่ต้องไม่ match', language: 'ระบุภาษาหรือ environment ที่จะนำ Regex ไปใช้' },
    expectedOutputTh: ['Regex', 'คำอธิบาย pattern', 'ตัวอย่าง valid/invalid และ edge cases'],
    exampleInputTh: 'Requirement: IPv4 address 4 octets 0–255 โดยไม่รับเลขเกินช่วง\nLanguage: JavaScript',
  }),
  DOCKER_GENERATOR: freezeMeta({
    descriptionTh: 'สร้างชุดตั้งค่า Docker ที่พร้อมใช้งานจริงใน Production',
    purposeTh: 'ใช้สร้าง Dockerfile และไฟล์ประกอบจาก application, technology และ requirement พร้อมคำนึงถึง security, caching, image size และ health check',
    useCasesTh: ['Containerize web app', 'เตรียม production image', 'ปรับ Docker setup ให้มี health check และ caching'],
    inputGuideTh: { application: 'อธิบาย application และวิธีทำงาน', technology: 'ระบุ runtime/framework และ version สำคัญ', requirements: 'ระบุ build/run command, port, environment และ dependency ที่จำเป็น' },
    expectedOutputTh: ['Dockerfile และ .dockerignore', 'compose/environment เมื่อจำเป็น', 'build/run/health-check instructions'],
    exampleInputTh: 'Application: Next.js app\nTechnology: Node.js 22, Next.js 16\nRequirements: production standalone, port 3000',
  }),
  API_DESIGNER: freezeMeta({
    descriptionTh: 'ออกแบบ REST API ที่พร้อมใช้งานจริงใน Production',
    purposeTh: 'ใช้แปลง requirement ของ application เป็น resource, endpoint, schema, auth, validation, error, pagination และ versioning ที่ตรวจสอบได้',
    useCasesTh: ['ออกแบบ backend API ใหม่', 'กำหนด contract ก่อน frontend/backend ทำงาน', 'review API surface ก่อน implement'],
    inputGuideTh: { application: 'อธิบายระบบและผู้ใช้หลัก', requirements: 'ระบุ use cases, data, auth และข้อจำกัดที่ API ต้องรองรับ' },
    expectedOutputTh: ['Resource/endpoint design', 'Request/response schema และ error model', 'Auth/validation/rate-limit/pagination strategy'],
    exampleInputTh: 'Application: ระบบ Ticket IT\nRequirements: create ticket, assign engineer, comments, attachment metadata, role-based access',
  }),
  DATABASE_SCHEMA_DESIGNER: freezeMeta({
    descriptionTh: 'ออกแบบโครงสร้างฐานข้อมูลเชิงสัมพันธ์และตาราง SQL',
    purposeTh: 'ใช้แปลง requirement ของระบบเป็น entities, tables, keys, relationships, indexes และ constraints พร้อมเหตุผลด้าน normalization',
    useCasesTh: ['ออกแบบฐานข้อมูลระบบใหม่', 'review relation/index ก่อนสร้างจริง', 'สร้าง SQL CREATE TABLE จาก requirement'],
    inputGuideTh: { system: 'อธิบายระบบและข้อมูลหลักที่ต้องจัดเก็บ', requirements: 'ระบุ business rules, relationships, query patterns และข้อจำกัด' },
    expectedOutputTh: ['Entity/table/relationship design', 'Keys/indexes/constraints', 'SQL CREATE TABLE และเหตุผล'],
    exampleInputTh: 'System: Prompt library\nRequirements: prompts, versions, runs, saved results และ user ownership',
  }),
  JSON_EXTRACTOR: freezeMeta({
    descriptionTh: 'ดึงข้อมูลแบบมีโครงสร้างและส่งคืน JSON ที่ถูกต้อง',
    purposeTh: 'ใช้แปลงข้อมูลต้นทางเป็น JSON ตาม schema ที่กำหนด โดยไม่เดาค่าที่ไม่มีและใช้ null เมื่อระบุไม่ได้',
    useCasesTh: ['Extract ข้อมูลจากข้อความ', 'เตรียมข้อมูลเข้า API', 'Normalize เอกสารตาม JSON schema'],
    inputGuideTh: { content: 'วางข้อมูลต้นทางที่ต้องการ extract', schema: 'วาง JSON schema หรือตัวอย่างโครงสร้าง key ที่ต้องการ' },
    expectedOutputTh: ['Valid JSON ตาม schema', 'ค่า null สำหรับข้อมูลที่หาไม่ได้'],
    exampleInputTh: 'Content: Ticket INC-1001, Site HQ, Status Open\nSchema: {"ticket":"","site":"","status":""}',
  }),
  TABLE_EXTRACTOR: freezeMeta({
    descriptionTh: 'แปลงข้อมูลที่ไม่มีโครงสร้างให้เป็นตารางที่มีโครงสร้าง',
    purposeTh: 'ใช้ดึง entity จากข้อความแล้วจัดเป็นหนึ่งรายการต่อแถวตาม columns ที่กำหนด โดยรักษาค่าต้นฉบับและไม่เดาค่าที่ขาด',
    useCasesTh: ['แปลงรายการข้อความเป็นตาราง', 'เตรียมข้อมูลสำหรับ Excel', 'รวมข้อมูลหลายรายการในรูปแบบเดียวกัน'],
    inputGuideTh: { content: 'วางข้อความหรือรายการต้นทาง', columns: 'ระบุชื่อคอลัมน์และลำดับที่ต้องการ' },
    expectedOutputTh: ['ตารางตาม columns ที่กำหนด', 'N/A สำหรับข้อมูลที่ไม่มี', 'ตัด duplicate ที่ชัดเจน'],
    exampleInputTh: 'Content: Ticket A site HQ owner Mek; Ticket B site Factory\nColumns: Ticket, Site, Owner',
  }),
  SENTIMENT_ANALYZER: freezeMeta({
    descriptionTh: 'วิเคราะห์ความรู้สึก อารมณ์ เจตนา และระดับความเร่งด่วนจากข้อความ',
    purposeTh: 'ใช้ประเมิน sentiment และ intent จากข้อความจริง พร้อมชี้ phrase ที่เป็นหลักฐานและความไม่แน่นอน เช่น sarcasm',
    useCasesTh: ['วิเคราะห์ customer feedback', 'คัดแยกข้อความเร่งด่วน', 'สำรวจอารมณ์และ intent ในข้อความ'],
    inputGuideTh: { text: 'วางข้อความเต็มที่ต้องการวิเคราะห์ โดยรักษาบริบทสำคัญ' },
    expectedOutputTh: ['Overall sentiment และคะแนน', 'Emotional signals/intent/urgency', 'เหตุผลจากข้อความ'],
    exampleInputTh: 'Text: “ระบบล่มอีกแล้ว งานลูกค้าหยุดหมด ช่วยดูด่วนครับ”',
  }),
  DATA_CLASSIFIER: freezeMeta({
    descriptionTh: 'จำแนกข้อมูลตามหมวดที่กำหนดและส่งคืน JSON แบบมีโครงสร้าง',
    purposeTh: 'ใช้จัด input เข้า category ที่ผู้ใช้กำหนดเท่านั้น พร้อม confidence, reason และ alternative โดยไม่สร้างหมวดใหม่เอง',
    useCasesTh: ['Classify ticket', 'จัดหมวด feedback', 'เตรียม routing rule จากข้อความ'],
    inputGuideTh: { input: 'วางข้อความหรือข้อมูลที่ต้องการจำแนก', categories: 'ระบุรายการ category ที่อนุญาตให้เลือก' },
    expectedOutputTh: ['JSON ที่มี category/confidence/reason', 'Alternative category เมื่อมีความคลุมเครือ'],
    exampleInputTh: 'Input: “ต่อ Wi-Fi ได้แต่ login 802.1X ไม่ผ่าน”\nCategories: Network, Account, Hardware',
  }),
  IMAGE_OBJECT_ANALYZER: freezeMeta({
    descriptionTh: 'วิเคราะห์วัตถุ สภาพแวดล้อม ข้อความ และรายละเอียดสำคัญในภาพ',
    purposeTh: 'ใช้สรุปสิ่งที่มองเห็นจากภาพโดยแยก observation ที่เห็นจริงออกจาก interpretation ที่ยังไม่แน่นอน',
    useCasesTh: ['ตรวจภาพอุปกรณ์หรือสถานที่', 'สรุปรายละเอียด visual', 'อ่านองค์ประกอบและข้อความที่มองเห็น'],
    inputGuideTh: { language: 'เลือกภาษาของคำอธิบายผลลัพธ์' },
    expectedOutputTh: ['วัตถุ/คน/สภาพแวดล้อมที่สังเกตได้', 'ข้อความและสี/วัสดุสำคัญ', 'รายละเอียดที่ไม่แน่นอนแยกต่างหาก'],
    exampleInputTh: 'แนบภาพอุปกรณ์หรือหน้าจอที่ต้องการให้ตรวจ พร้อมเลือกภาษาผลลัพธ์เป็น Thai',
  }),
  IMAGE_TO_JSON: freezeMeta({
    descriptionTh: 'ดึงข้อมูลแบบมีโครงสร้างจากภาพและส่งคืน JSON',
    purposeTh: 'ใช้ extract ข้อมูลที่มองเห็นจากภาพตาม schema ที่กำหนด โดยไม่เดาสิ่งที่อ่านไม่ได้และใช้ null เมื่อไม่ทราบ',
    useCasesTh: ['อ่านป้าย/ฟอร์มเป็น JSON', 'แปลงภาพสินค้าเป็นข้อมูล', 'Extract field จาก screenshot'],
    inputGuideTh: { schema: 'กำหนด key และโครงสร้าง JSON ที่ต้องการจากภาพ' },
    expectedOutputTh: ['Valid JSON ตาม schema', 'null สำหรับ field ที่ระบุไม่ได้จากภาพ'],
    exampleInputTh: 'แนบภาพฉลากสินค้า\nSchema: {"product":"","model":"","serial":""}',
  }),
  VIDEO_QA: freezeMeta({
    descriptionTh: 'วิเคราะห์วิดีโอและตอบคำถามโดยอ้างอิงหลักฐานตามเวลา',
    purposeTh: 'ใช้ตอบคำถามจากวิดีโอที่ให้มา พร้อม timestamp และ observed evidence โดยแยก observation ออกจาก interpretation',
    useCasesTh: ['หาช่วงเหตุการณ์ในวิดีโอ', 'ตรวจขั้นตอนจาก recording', 'ตอบคำถามพร้อม timestamp'],
    inputGuideTh: { question: 'ถามสิ่งที่ต้องการตรวจจากวิดีโอให้ชัดเจน' },
    expectedOutputTh: ['คำตอบตรงคำถาม', 'Timestamp และหลักฐานที่สังเกตได้', 'Confidence/uncertainty'],
    exampleInputTh: 'Question: ช่วงไหนในวิดีโอที่ link status เปลี่ยนจาก up เป็น down?',
  }),
  AUDIO_TRANSCRIBER: freezeMeta({
    descriptionTh: 'ถอดเสียงโดยแยกผู้พูดและใส่เวลา',
    purposeTh: 'ใช้ถอดเสียงจากไฟล์ audio พร้อม speaker separation, timestamps และทำเครื่องหมายส่วนที่ฟังไม่ชัดแทนการเดาคำ',
    useCasesTh: ['ถอดประชุม', 'ถอด interview', 'ทำ transcript พร้อม timestamp'],
    inputGuideTh: { language: 'เลือกภาษาที่ต้องการใช้กับคำอธิบาย/รูปแบบผลลัพธ์' },
    expectedOutputTh: ['Transcript แยกผู้พูด', 'Timestamp', 'จุดที่ฟังไม่ชัดถูกระบุชัด'],
    exampleInputTh: 'แนบไฟล์เสียงประชุมและเลือก Thai เพื่อให้หัวข้อ/คำอธิบายเป็นภาษาไทย',
  }),
  BLOG_GENERATOR: freezeMeta({
    descriptionTh: 'สร้างบทความบล็อกแบบยาวที่มีโครงสร้างชัดเจน',
    purposeTh: 'ใช้สร้าง blog draft ตาม topic, audience, tone และความยาว โดยจัด narrative ให้ครบ introduction, sections, examples, advice และ conclusion',
    useCasesTh: ['ร่างบทความความรู้', 'สร้าง long-form content', 'ปรับเนื้อหาให้เหมาะกับ audience'],
    inputGuideTh: { topic: 'ระบุหัวข้อและขอบเขต', audience: 'ระบุกลุ่มผู้อ่าน', tone: 'ระบุโทน เช่น professional หรือ friendly', length: 'ระบุความยาวเป้าหมาย เช่น 1200 คำ' },
    expectedOutputTh: ['Title/Introduction/Sections', 'ตัวอย่างหรือคำแนะนำที่สัมพันธ์กับหัวข้อ', 'Conclusion ที่ไม่ซ้ำเนื้อหา'],
    exampleInputTh: 'Topic: วิธีวิเคราะห์ Packet Loss\nAudience: Junior Network Engineer\nTone: Practical\nLength: 1200 words',
  }),
  SEO_CONTENT_WRITER: freezeMeta({
    descriptionTh: 'สร้างบทความเน้น SEO พร้อม Metadata โครงสร้าง และ FAQ',
    purposeTh: 'ใช้สร้าง SEO content package จาก topic, keyword และ audience โดยวาง keyword อย่างเป็นธรรมชาติและหลีกเลี่ยง keyword stuffing',
    useCasesTh: ['สร้าง SEO article', 'เตรียม metadata/slug/FAQ', 'วาง heading structure จาก keyword'],
    inputGuideTh: { topic: 'ระบุหัวข้อหลัก', primary_keyword: 'ระบุ keyword หลักหนึ่งคำหรือวลี', secondary_keywords: 'ระบุ keyword รองที่เกี่ยวข้อง', audience: 'ระบุกลุ่มผู้อ่านและ intent' },
    expectedOutputTh: ['SEO title/meta/slug', 'H1/H2/H3 structure และ article', 'FAQ และ internal-link suggestions'],
    exampleInputTh: 'Topic: Cisco VLAN Troubleshooting\nPrimary keyword: troubleshoot VLAN\nSecondary keywords: trunk, access port\nAudience: IT Support',
  }),
  SOCIAL_CONTENT_GENERATOR: freezeMeta({
    descriptionTh: 'สร้างคอนเทนต์โซเชียลสำหรับแพลตฟอร์มและกลุ่มเป้าหมายต่าง ๆ',
    purposeTh: 'ใช้สร้างหลาย post จาก topic เดียว โดยกำหนด platform, audience และ tone พร้อมเปลี่ยนมุม creative ไม่ให้ซ้ำกัน',
    useCasesTh: ['สร้าง social campaign drafts', 'แตกหลายมุมจากหัวข้อเดียว', 'ปรับข้อความให้เหมาะกับ platform'],
    inputGuideTh: { count: 'ระบุจำนวน post ที่ต้องการ', topic: 'ระบุหัวข้อหรือ campaign', platform: 'ระบุแพลตฟอร์ม เช่น LinkedIn, Facebook, X', audience: 'ระบุกลุ่มเป้าหมาย', tone: 'ระบุโทนภาษา' },
    expectedOutputTh: ['หลาย post ที่มี hook/main content/CTA', 'มุม creative ที่แตกต่างกัน'],
    exampleInputTh: 'Count: 3\nTopic: เปิดตัวระบบ Helpdesk ใหม่\nPlatform: LinkedIn\nAudience: IT Managers\nTone: Professional',
  }),
  MEETING_SUMMARIZER: freezeMeta({
    descriptionTh: 'สรุปการประชุม ประเด็นตัดสินใจ ความเสี่ยง และขั้นตอนถัดไป',
    purposeTh: 'ใช้เปลี่ยน transcript การประชุมเป็น summary ที่แยก decisions, discussion, questions, risks และ next steps โดยไม่สร้างข้อมูลที่ไม่ได้กล่าวไว้',
    useCasesTh: ['สรุปประชุมทีม', 'เตรียม minutes หลัง call', 'หาคำถามค้างและความเสี่ยง'],
    inputGuideTh: { transcript: 'วาง transcript หรือ notes ของการประชุมให้ครบเท่าที่มี' },
    expectedOutputTh: ['Meeting summary', 'Decisions/open questions/risks', 'Next steps จากข้อมูลที่กล่าวจริง'],
    exampleInputTh: 'Transcript: “ทีมตกลง deploy วันศุกร์ หาก regression test ผ่าน ...”',
  }),
  ACTION_ITEM_EXTRACTOR: freezeMeta({
    descriptionTh: 'ดึงรายการงานที่ต้องทำจากประชุม เอกสาร หรือโน้ต',
    purposeTh: 'ใช้ดึง task ที่ actionable พร้อม owner, priority, deadline, status และ dependency โดยไม่สร้าง owner/deadline เมื่อข้อมูลไม่ระบุ',
    useCasesTh: ['แปลง meeting notes เป็น task list', 'ดึง follow-up จากเอกสาร', 'เตรียมรายการงานให้ทีม'],
    inputGuideTh: { content: 'วาง meeting notes, transcript หรือเอกสารที่มี action items' },
    expectedOutputTh: ['ตาราง action items', 'Unassigned/Not specified เมื่อข้อมูลไม่มี'],
    exampleInputTh: 'Content: “Mek ตรวจ switch log ภายในวันศุกร์ ส่วน owner ของการอัปเดตเอกสารยังไม่ระบุ”',
  }),
  PRESENTATION_BUILDER: freezeMeta({
    descriptionTh: 'สร้างโครงงานนำเสนอแบบสไลด์พร้อม Speaker Notes',
    purposeTh: 'ใช้วาง narrative ของ presentation จาก topic, audience และจำนวนสไลด์ พร้อม main message, bullets, visual idea และ speaker notes ต่อสไลด์',
    useCasesTh: ['เตรียม presentation งาน', 'สร้างโครง deck ก่อนออกแบบ', 'วางเรื่องราวจาก intro ถึง conclusion'],
    inputGuideTh: { topic: 'ระบุหัวข้อและเป้าหมายของ presentation', audience: 'ระบุกลุ่มผู้ฟัง', slides: 'ระบุจำนวนสไลด์ที่ต้องการ' },
    expectedOutputTh: ['Outline รายสไลด์', 'Main message/bullets/visual suggestion', 'Speaker notes'],
    exampleInputTh: 'Topic: Network Modernization Plan\nAudience: IT Management\nSlides: 8',
  }),
  PERSONAL_TUTOR: freezeMeta({
    descriptionTh: 'ติวเรื่องที่กำหนดแบบโต้ตอบ พร้อมคำอธิบาย ตัวอย่าง คำถาม และแบบฝึกหัด',
    purposeTh: 'ใช้เรียนแบบ step-by-step ตามระดับและเป้าหมาย โดยถามความเข้าใจ ปรับแก้ misconception และเพิ่มความยากทีละขั้น',
    useCasesTh: ['เรียนหัวข้อใหม่', 'ทบทวนก่อนสอบ', 'ฝึกจาก concept ไปสู่แบบฝึกหัด'],
    inputGuideTh: { subject: 'ระบุวิชาหรือหัวข้อ', level: 'ระบุระดับปัจจุบัน', goal: 'ระบุสิ่งที่อยากทำได้หลังเรียน' },
    expectedOutputTh: ['คำอธิบายและตัวอย่าง', 'คำถามตรวจความเข้าใจ', 'แบบฝึกหัดที่ยังไม่เฉลยก่อนผู้เรียนลอง'],
    exampleInputTh: 'Subject: OSPF\nLevel: Beginner\nGoal: อ่าน routing table และเข้าใจ neighbor adjacency',
  }),
  QUIZ_GENERATOR: freezeMeta({
    descriptionTh: 'สร้างแบบทดสอบพร้อมคำตอบและคำอธิบาย',
    purposeTh: 'ใช้สร้าง quiz ตาม topic, difficulty, จำนวนข้อ และ question types โดยกระจายคำถามให้ครอบคลุม concept สำคัญ',
    useCasesTh: ['ทบทวนก่อนสอบ', 'สร้าง quiz สำหรับทีม', 'ตรวจความเข้าใจหลังเรียน'],
    inputGuideTh: { topic: 'ระบุหัวข้อที่จะออกข้อสอบ', difficulty: 'ระบุระดับความยาก', count: 'ระบุจำนวนคำถาม', question_types: 'ระบุรูปแบบ เช่น multiple choice, short answer' },
    expectedOutputTh: ['คำถามตามจำนวนที่กำหนด', 'ตัวเลือกเมื่อเหมาะสม', 'คำตอบที่ถูกและคำอธิบาย'],
    exampleInputTh: 'Topic: VLAN & Trunk\nDifficulty: Intermediate\nCount: 10\nQuestion types: Multiple choice + scenario',
  }),
});
