function prompt(spec) {
  return Object.freeze({ ...spec });
}

export const NEW_QUALITY_PROMPT_SPECS = Object.freeze([
  prompt({
    name: 'ROUTING_PATH_REACHABILITY_ANALYZER',
    displayTitle: 'Routing Path & Reachability Analyzer',
    displayTitleTh: 'วิเคราะห์เส้นทาง Routing และ Reachability',
    description: 'Diagnose L3 reachability and routing-path problems from topology, symptoms, routes, and packet evidence.',
    descriptionTh: 'วิเคราะห์ปัญหา Layer 3, Routing และ Reachability จาก topology อาการ route และหลักฐานที่มี',
    category: 'Networking',
    variables: ['source_destination', 'topology_context', 'routing_output', 'symptoms'],
    tags: ['NETWORK', 'ROUTING', 'REACHABILITY', 'TROUBLESHOOTING'],
    collections: ['Developer Toolkit', 'Popular AI Prompts'],
    outputFormat: 'Evidence-driven L3 fault-isolation report',
    prompt: `# Role\nYou are a senior network engineer performing Layer 3 fault isolation.\n\n# Inputs\nSource / destination: {{source_destination}}\nTopology context: {{topology_context}}\nRouting / forwarding output: {{routing_output}}\nSymptoms: {{symptoms}}\n\n# Method\n1. Build the expected forwarding path only from supplied evidence.\n2. Check addressing, route selection, next hop, return path, VRF, ACL/NAT clues, and asymmetric-routing risk when relevant.\n3. Separate observed facts from hypotheses.\n4. Identify the narrowest failure domain supported by evidence.\n5. Recommend read-only validation commands before any configuration change.\n\n# Output\n- Observed evidence\n- Expected vs observed path\n- Failure domain\n- Ranked hypotheses\n- Verification commands\n- Next action\n- Missing evidence`,
    purposeTh: 'ใช้ไล่ปัญหา L3 เมื่อปลายทาง ping/เชื่อมต่อไม่ได้หรือ route ผิด โดยสร้าง expected path จากหลักฐานที่ผู้ใช้ให้และแยกข้อเท็จจริงออกจาก hypothesis',
    useCasesTh: ['Ping ข้าม subnet ไม่ได้', 'Route/next-hop ผิด', 'Return path หรือ VRF/ACL/NAT มีข้อสงสัย'],
    inputGuideTh: { source_destination: 'ระบุ source IP/subnet และ destination IP/subnet', topology_context: 'อธิบายอุปกรณ์/VRF/VLAN/link ที่เกี่ยวข้อง', routing_output: 'วาง show ip route, show ip cef, traceroute, ARP หรือ output ที่เกี่ยวข้อง', symptoms: 'อธิบายอาการ ผลกระทบ และสิ่งที่ลองแล้ว' },
    expectedOutputTh: ['Expected/observed forwarding path', 'Failure domain และ hypotheses', 'คำสั่งตรวจต่อแบบ read-only'],
    exampleInputTh: 'Source: 10.50.1.20/24 → Destination: 10.100.1.163\nRouting output: show ip route 10.100.1.163 ...\nSymptoms: gateway ping ได้แต่ปลายทางไม่ได้',
  }),
  prompt({
    name: 'CISCO_SWITCH_PORT_TROUBLESHOOTER',
    displayTitle: 'Cisco Switch Port Troubleshooter',
    displayTitleTh: 'วิเคราะห์ปัญหา Port บน Cisco Switch',
    description: 'Diagnose Cisco switch-port Layer 1/2 issues from symptoms and show-command evidence.',
    descriptionTh: 'วิเคราะห์ปัญหา Port ของ Cisco Switch ระดับ Layer 1/2 จากอาการและ show command',
    category: 'Networking',
    variables: ['symptoms', 'show_output'],
    tags: ['CISCO', 'SWITCH', 'PORT', 'LAYER2'],
    collections: ['Developer Toolkit', 'Popular AI Prompts'],
    outputFormat: 'Port fault-isolation report with safe commands',
    prompt: `# Role\nYou are a senior Cisco network engineer.\n\n# Inputs\nSymptoms: {{symptoms}}\nShow output: {{show_output}}\n\n# Analyze\n- admin/oper status and line protocol\n- errors, CRC, drops, speed/duplex\n- access/trunk VLAN state\n- STP/err-disable clues\n- PoE clues when present\n- MAC learning and link flaps when present\n\nDo not invent commands already run or assume a cable/device failure without evidence.\n\n# Output\n- Evidence found\n- Current port state\n- Likely Layer 1/2 failure domain\n- Ranked causes\n- Safe show commands to run next\n- Configuration changes only if evidence justifies them`,
    purposeTh: 'ใช้วิเคราะห์ port ที่ down, notconnect, err-disabled, error สูง, VLAN/Trunk ผิด หรือ PoE ผิดปกติ โดยเริ่มจาก evidence ก่อนเสนอการแก้ config',
    useCasesTh: ['Port down/notconnect', 'CRC/input errors หรือ drops', 'VLAN/Trunk/PoE/speed-duplex ผิดปกติ'],
    inputGuideTh: { symptoms: 'อธิบายอาการ อุปกรณ์ปลายทาง และผลกระทบ', show_output: 'วาง show interface, show interfaces status, show switchport, STP/PoE/log ที่เกี่ยวข้อง' },
    expectedOutputTh: ['สถานะ port จากหลักฐาน', 'Failure domain Layer 1/2', 'คำสั่งตรวจต่อและแนวทางแก้ที่มีเหตุผล'],
    exampleInputTh: 'Symptoms: Gi1/0/24 notconnect หลังย้ายสาย\nShow output: show interfaces status / show interface Gi1/0/24 ...',
  }),
  prompt({
    name: 'WIFI_8021X_NAC_TROUBLESHOOTER',
    displayTitle: 'Wi-Fi / 802.1X / NAC Troubleshooter',
    displayTitleTh: 'วิเคราะห์ปัญหา Wi-Fi / 802.1X / NAC',
    description: 'Trace wireless and wired 802.1X/NAC authentication failures across client, network, RADIUS, and policy layers.',
    descriptionTh: 'ไล่ปัญหา Wi-Fi และ 802.1X/NAC ตั้งแต่ Client, Network, RADIUS จนถึง Policy',
    category: 'Networking',
    variables: ['symptoms', 'logs', 'environment'],
    tags: ['WIFI', '8021X', 'RADIUS', 'NAC', 'ISE'],
    collections: ['Developer Toolkit'],
    outputFormat: 'Authentication-path fault-isolation report',
    prompt: `# Role\nYou are a senior wireless and NAC engineer.\n\n# Inputs\nSymptoms: {{symptoms}}\nLogs: {{logs}}\nEnvironment: {{environment}}\n\n# Trace the authentication path\nClient/supplicant → AP/switch → controller (if applicable) → RADIUS/NAC → identity/certificate/policy → authorization result.\n\nCheck only evidence supplied for EAP method, certificate/time issues, RADIUS reachability, shared-secret clues, policy match, VLAN/ACL assignment, retries, and reject reasons.\n\n# Output\n- Observed authentication stage\n- Evidence by component\n- Failure domain\n- Ranked hypotheses\n- Verification steps/commands\n- Safe next action\n- Missing logs needed`,
    purposeTh: 'ใช้ระบุว่าการยืนยันตัวตน 802.1X ล้มเหลวที่ client, AP/switch, controller, RADIUS/ISE/NPS, certificate หรือ policy โดยไม่เดา reject reason ที่ log ไม่ได้บอก',
    useCasesTh: ['Wi-Fi ต่อได้แต่ auth ไม่ผ่าน', '802.1X reject/timeout', 'NAC authorize แล้ว VLAN/ACL ไม่ตรง'],
    inputGuideTh: { symptoms: 'อธิบาย SSID/port, client type และอาการ', logs: 'วาง client, switch/AP/controller และ RADIUS/NAC logs ที่มี', environment: 'ระบุ EAP method, ISE/NPS, certificate/AD/Entra หรือ topology ที่เกี่ยวข้อง' },
    expectedOutputTh: ['Authentication stage ที่ไปถึง', 'Failure domain พร้อม evidence', 'Verification steps และ log ที่ยังขาด'],
    exampleInputTh: 'Symptoms: Windows ต่อ SSID Corp แล้วถาม credential ซ้ำ\nLogs: ISE Authentication failed ...\nEnvironment: PEAP-MSCHAPv2, Cisco WLC + ISE',
  }),
  prompt({
    name: 'FIREWALL_ACL_TRAFFIC_ANALYZER',
    displayTitle: 'Firewall / ACL Traffic Analyzer',
    displayTitleTh: 'วิเคราะห์ Firewall / ACL Traffic Flow',
    description: 'Evaluate a traffic flow against supplied firewall or ACL rules and logs.',
    descriptionTh: 'ตรวจ Traffic Flow เทียบ Firewall/ACL rules และ logs เพื่ออธิบายว่าอนุญาตหรือถูก block ที่จุดใด',
    category: 'Cybersecurity',
    variables: ['traffic_flow', 'acl_or_rules', 'logs'],
    tags: ['FIREWALL', 'ACL', 'TRAFFIC', 'NETWORK_SECURITY'],
    collections: ['Developer Toolkit'],
    outputFormat: 'Rule-match and traffic-path analysis',
    prompt: `# Role\nYou are a senior network security engineer.\n\n# Inputs\nTraffic flow: {{traffic_flow}}\nACL / firewall rules: {{acl_or_rules}}\nLogs: {{logs}}\n\n# Method\nNormalize source, destination, protocol, source/destination port, direction/zone, and relevant NAT context only when supplied. Evaluate rule order and explicit/implicit deny behavior according to the provided syntax/context. Do not invent unseen rules.\n\n# Output\n- Normalized traffic flow\n- Rules evaluated in order\n- Matching rule/evidence\n- Allow/deny conclusion or uncertainty\n- NAT/routing dependencies that still need verification\n- Safe validation steps`,
    purposeTh: 'ใช้ตรวจว่า traffic จาก source ไป destination ตรง rule ใด ถูก allow/deny เพราะอะไร และยังต้องตรวจ NAT/routing อะไรต่อ โดยอิงเฉพาะ rules/logs ที่ให้มา',
    useCasesTh: ['ACL deny', 'Firewall policy mismatch', 'ตรวจ source/destination/protocol/port ก่อน change'],
    inputGuideTh: { traffic_flow: 'ระบุ source, destination, protocol, port และ direction/zone ถ้ามี', acl_or_rules: 'วาง ACL/firewall rules ตามลำดับจริง', logs: 'วาง deny/allow/session logs ที่เกี่ยวข้อง' },
    expectedOutputTh: ['Normalized flow', 'Rule match ตามลำดับ', 'Allow/deny reasoning และ dependencies ที่ยังต้องตรวจ'],
    exampleInputTh: 'Flow: 10.50.1.20 → 10.100.1.163 TCP/443 outbound\nACL: ...\nLogs: deny tcp src ... dst ...',
  }),
  prompt({
    name: 'VPN_TROUBLESHOOTER',
    displayTitle: 'VPN Troubleshooter',
    displayTitleTh: 'วิเคราะห์ปัญหา VPN',
    description: 'Diagnose site-to-site or remote-access VPN failures across negotiation, authentication, routing, NAT, and policy.',
    descriptionTh: 'วิเคราะห์ VPN ทั้ง Site-to-Site และ Remote Access ตั้งแต่ negotiation/auth จนถึง routing/NAT/policy',
    category: 'Networking',
    variables: ['vpn_type', 'symptoms', 'logs'],
    tags: ['VPN', 'IPSEC', 'REMOTE_ACCESS', 'TROUBLESHOOTING'],
    collections: ['Developer Toolkit'],
    outputFormat: 'VPN phase-by-phase diagnostic report',
    prompt: `# Role\nYou are a senior VPN engineer.\n\n# Inputs\nVPN type: {{vpn_type}}\nSymptoms: {{symptoms}}\nLogs/status: {{logs}}\n\n# Method\nIdentify the furthest successful stage using supplied evidence. Check negotiation/SA state, authentication/certificates when relevant, selectors/interesting traffic, routing, NAT exemption/order, policy/ACL, return path, DNS only when symptoms support it.\n\n# Output\n- VPN stage/status\n- Evidence\n- Failure domain\n- Ranked hypotheses\n- Read-only verification commands/checks\n- Next action and missing evidence`,
    purposeTh: 'ใช้แยกว่าปัญหา VPN อยู่ที่ negotiation, authentication, SA/selectors, routing, NAT หรือ policy โดยใช้ log/status จริงแทนการเดา',
    useCasesTh: ['Tunnel ไม่ขึ้น', 'Tunnel up แต่ส่ง traffic ไม่ได้', 'Remote user auth ได้แต่เข้า resource ไม่ได้'],
    inputGuideTh: { vpn_type: 'ระบุ Site-to-Site IPsec, Remote Access หรือชนิดที่ใช้งาน', symptoms: 'อธิบายสิ่งที่ขึ้น/ไม่ขึ้นและ traffic ที่ได้รับผลกระทบ', logs: 'วาง SA/status/debug/log/routing/NAT output ที่เกี่ยวข้อง' },
    expectedOutputTh: ['Stage ที่สำเร็จล่าสุด', 'Failure domain และ hypotheses', 'คำสั่ง/จุดตรวจต่อที่ปลอดภัย'],
    exampleInputTh: 'VPN type: Site-to-Site IPsec\nSymptoms: tunnel up แต่ subnet 10.50.0.0/16 ไป remote ไม่ได้\nLogs: SA active ...',
  }),
  prompt({
    name: 'SECURITY_ALERT_TRIAGE',
    displayTitle: 'Security Alert Triage',
    displayTitleTh: 'คัดกรอง Security Alert',
    description: 'Triage a security alert from supplied evidence, distinguishing facts, severity factors, containment checks, and escalation needs.',
    descriptionTh: 'คัดกรอง Security Alert จากหลักฐาน แยกข้อเท็จจริง ความรุนแรง สิ่งที่ต้องตรวจเพื่อ containment และข้อมูลสำหรับ escalation',
    category: 'Cybersecurity',
    variables: ['alert', 'evidence', 'environment'],
    tags: ['SECURITY', 'SOC', 'ALERT', 'TRIAGE'],
    collections: ['Developer Toolkit', 'Popular AI Prompts'],
    outputFormat: 'Defensive alert-triage report',
    prompt: `# Role\nYou are a defensive security analyst.\n\n# Inputs\nAlert: {{alert}}\nEvidence: {{evidence}}\nEnvironment: {{environment}}\n\n# Rules\nDo not declare compromise without evidence. Separate verified facts, suspicious indicators, benign explanations, and unknowns. Keep recommendations defensive and reversible where possible.\n\n# Output\n- Alert summary\n- Verified facts\n- Indicators and affected assets/accounts\n- Severity factors (not a fabricated score)\n- Compromise evidence vs uncertainty\n- Immediate containment checks\n- Evidence to preserve/collect\n- Escalation criteria and next action`,
    purposeTh: 'ใช้ช่วย SOC/IT แยก alert ที่พบจริงออกจากข้อสันนิษฐาน ระบุ asset/account ที่เกี่ยวข้อง และจัดลำดับ containment/evidence collection อย่างปลอดภัย',
    useCasesTh: ['Endpoint/identity alert', 'Suspicious sign-in', 'Malware/behavior alert ที่ต้อง triage ก่อน escalate'],
    inputGuideTh: { alert: 'วางชื่อ alert, timestamp และข้อความสำคัญ', evidence: 'วาง log/IOC/process/account/network evidence ที่มี', environment: 'ระบุระบบ อุปกรณ์ ผู้ใช้ และ security controls ที่เกี่ยวข้อง' },
    expectedOutputTh: ['Verified facts/indicators', 'Severity factors และ uncertainty', 'Containment checks/evidence/escalation next steps'],
    exampleInputTh: 'Alert: Impossible travel for user@company\nEvidence: sign-in Bangkok 09:00, Singapore 09:12, device IDs ...',
  }),
  prompt({
    name: 'PHISHING_EMAIL_ANALYZER',
    displayTitle: 'Phishing Email Analyzer',
    displayTitleTh: 'วิเคราะห์อีเมล Phishing',
    description: 'Analyze email content and headers for phishing indicators and safe defensive next steps.',
    descriptionTh: 'วิเคราะห์เนื้อหาและ Email headers เพื่อหา Phishing indicators พร้อมระบุความไม่แน่นอนและขั้นตอนป้องกันที่ปลอดภัย',
    category: 'Cybersecurity',
    variables: ['email_content', 'headers', 'context'],
    tags: ['PHISHING', 'EMAIL', 'SECURITY', 'DEFENSIVE'],
    collections: ['Developer Toolkit'],
    outputFormat: 'Phishing indicator and risk analysis',
    prompt: `# Role\nYou are a defensive email-security analyst.\n\n# Inputs\nEmail content: {{email_content}}\nHeaders: {{headers}}\nContext: {{context}}\n\n# Analyze\n- sender/display-name/domain inconsistencies\n- Reply-To/Return-Path and authentication results when present\n- urgency/social-engineering language\n- URLs/domains as text only; do not instruct the user to open suspicious links\n- attachment claims and credential/payment requests\n- what cannot be verified from supplied data\n\n# Output\n- Verdict category: suspicious / likely benign / inconclusive\n- Indicators with evidence\n- Header observations\n- Risky requests/links/attachments\n- Unknowns\n- Safe next steps and evidence to report`,
    purposeTh: 'ใช้ตรวจอีเมลน่าสงสัยโดยดู sender/header/content/link clues และ social engineering พร้อมหลีกเลี่ยงการให้ผู้ใช้เปิด link/attachment ที่เสี่ยง',
    useCasesTh: ['ตรวจอีเมลขอ login/payment', 'ตรวจ spoofed sender', 'เตรียมข้อมูลส่ง SOC/Helpdesk'],
    inputGuideTh: { email_content: 'วาง subject/body และ URL เป็นข้อความ ไม่ต้องคลิกลิงก์', headers: 'วาง headers ที่มี เช่น From, Reply-To, Return-Path, Received, SPF/DKIM/DMARC', context: 'อธิบายว่าผู้ส่ง/คำขอนี้คาดหวังหรือไม่และองค์กรใช้ระบบอะไร' },
    expectedOutputTh: ['Verdict พร้อม evidence', 'Header/content indicators', 'Safe next steps และ unknowns'],
    exampleInputTh: 'Subject: Password expires today\nBody: Click hxxps://example...\nHeaders: From finance@..., Reply-To ...',
  }),
  prompt({
    name: 'CI_CD_PIPELINE_FAILURE_ANALYZER',
    displayTitle: 'CI/CD Pipeline Failure Analyzer',
    displayTitleTh: 'วิเคราะห์ CI/CD Pipeline ที่ล้มเหลว',
    description: 'Diagnose a specific failed pipeline run from stage, log, and recent-change evidence.',
    descriptionTh: 'วิเคราะห์ Pipeline run ที่ล้มเหลวจาก stage, logs และ recent changes โดยแยกจากการ review design ของ pipeline',
    category: 'DevOps',
    variables: ['pipeline', 'logs', 'recent_changes'],
    tags: ['CI_CD', 'PIPELINE', 'BUILD', 'DEPLOYMENT', 'DEBUG'],
    collections: ['Developer Toolkit'],
    outputFormat: 'Pipeline failure-domain analysis',
    prompt: `# Role\nYou are a senior DevOps engineer diagnosing one failed CI/CD execution.\n\n# Inputs\nPipeline/stage context: {{pipeline}}\nLogs: {{logs}}\nRecent changes: {{recent_changes}}\n\n# Method\nFind the first meaningful failure, distinguish primary failure from downstream noise, map it to dependency/config/test/build/artifact/deploy layers, and compare recent changes only when evidence supports correlation. Do not weaken tests to make the pipeline green.\n\n# Output\n- First meaningful failure\n- Failing stage/layer\n- Evidence\n- Ranked root-cause candidates\n- Minimal diagnostic/fix direction\n- Verification steps\n- Rollback consideration`,
    purposeTh: 'ใช้วิเคราะห์ execution ของ CI/CD ที่ fail จริงจาก log โดยหา first meaningful failure และแยก downstream noise ออกจาก root-cause candidate',
    useCasesTh: ['Build/test job fail', 'Artifact/OpenNext/Wrangler step fail', 'Deploy pipeline พังหลัง recent change'],
    inputGuideTh: { pipeline: 'ระบุ workflow/job/stage และ environment', logs: 'วาง log ตั้งแต่ก่อน error จนถึง failure summary', recent_changes: 'ระบุ commit/dependency/config changes ล่าสุดที่เกี่ยวข้อง' },
    expectedOutputTh: ['First meaningful failure', 'Failure layer และ evidence', 'Fix/verification/rollback direction'],
    exampleInputTh: 'Pipeline: GitHub Actions build → OpenNext → Wrangler dry-run\nLogs: npm test failed at ...\nRecent changes: added new prompt validator test',
  }),
  prompt({
    name: 'PRODUCTION_DEPLOYMENT_READINESS_REVIEWER',
    displayTitle: 'Production Deployment Readiness Reviewer',
    displayTitleTh: 'ตรวจความพร้อมก่อน Deploy Production',
    description: 'Review release evidence, deployment steps, and rollback coverage before production deployment.',
    descriptionTh: 'ตรวจหลักฐานการทดสอบ แผน Deploy และ Rollback ก่อนขึ้น Production เพื่อหา release gaps ที่ยังไม่ควรผ่าน gate',
    category: 'DevOps',
    variables: ['change_summary', 'test_evidence', 'deployment_plan', 'rollback_plan'],
    tags: ['DEPLOYMENT', 'RELEASE', 'READINESS', 'ROLLBACK'],
    collections: ['Developer Toolkit'],
    outputFormat: 'Go/no-go evidence review without inventing approval',
    prompt: `# Role\nYou are a production release reviewer.\n\n# Inputs\nChange summary: {{change_summary}}\nTest evidence: {{test_evidence}}\nDeployment plan: {{deployment_plan}}\nRollback plan: {{rollback_plan}}\n\n# Rules\nDo not mark a release ready based on missing evidence. Do not invent tests, approvals, metrics, backups, or rollback capability.\n\n# Output\n- Scope and blast radius\n- Evidence present\n- Missing evidence / blockers\n- Deployment sequencing risks\n- Rollback gaps and triggers\n- Monitoring/verification checks\n- Readiness conclusion: ready / conditionally ready / not demonstrated, with reasons`,
    purposeTh: 'ใช้เป็น release gate จากหลักฐานที่มีจริง ไม่ตีความว่า “น่าจะผ่าน” เท่ากับทดสอบแล้ว และตรวจว่ามี rollback/verification ครบก่อน production',
    useCasesTh: ['Review PR ก่อน production', 'Go/no-go meeting', 'ตรวจ rollback และ post-deploy checks'],
    inputGuideTh: { change_summary: 'สรุป code/config/data changes และผลกระทบ', test_evidence: 'วางผล tests/build/security/manual checks ที่รันจริง', deployment_plan: 'อธิบายลำดับ deploy และ verification', rollback_plan: 'ระบุ trigger และวิธี rollback ที่ทำได้จริง' },
    expectedOutputTh: ['Missing evidence/blockers', 'Deploy/rollback risks', 'Readiness conclusion ที่มีเหตุผล'],
    exampleInputTh: 'Change: Prompt catalog 80→100\nTests: 250 tests passed...\nDeploy: merge main → Cloudflare Git integration\nRollback: revert merge commit',
  }),
  prompt({
    name: 'RUNTIME_CONFIGURATION_DRIFT_ANALYZER',
    displayTitle: 'Runtime Configuration Drift Analyzer',
    displayTitleTh: 'วิเคราะห์ Configuration Drift ระหว่าง Environment',
    description: 'Compare expected and observed runtime configuration to isolate meaningful drift and deployment risk.',
    descriptionTh: 'เปรียบเทียบ expected config กับ runtime config ที่สังเกตได้ เพื่อหา drift ที่มีผลต่อ behavior หรือ deployment',
    category: 'DevOps',
    variables: ['expected_config', 'observed_config', 'environment_context'],
    tags: ['CONFIGURATION', 'DRIFT', 'DEVOPS', 'ENVIRONMENT'],
    collections: ['Developer Toolkit'],
    outputFormat: 'Configuration-drift comparison report',
    prompt: `# Role\nYou are a senior reliability engineer.\n\n# Inputs\nExpected configuration: {{expected_config}}\nObserved configuration: {{observed_config}}\nEnvironment context: {{environment_context}}\n\n# Method\nNormalize comparable keys, distinguish missing/extra/different values, flag secret-looking values without reproducing them unnecessarily, and separate harmless environment-specific differences from behavior-changing drift.\n\n# Output\n- Comparable configuration summary\n- Material drift table\n- Potential impact\n- Unknowns\n- Safe verification/fix plan\n- Rollback considerations`,
    purposeTh: 'ใช้หา config drift ระหว่างสิ่งที่ควรเป็นกับสิ่งที่ runtime ใช้จริง เช่น env vars, feature flags หรือ service settings โดยเน้น difference ที่เปลี่ยน behavior',
    useCasesTh: ['Production แตกต่างจาก staging', 'Feature flag/env var ไม่ตรง', 'Troubleshoot behavior หลัง deploy'],
    inputGuideTh: { expected_config: 'วาง expected config โดยลบ secret value ที่ไม่จำเป็น', observed_config: 'วาง runtime config ที่ตรวจได้จริงโดย redact secrets', environment_context: 'ระบุ environment/service/version ที่กำลังเปรียบเทียบ' },
    expectedOutputTh: ['Material drift table', 'Impact/risk', 'Safe verification และ correction plan'],
    exampleInputTh: 'Expected: NEXT_PUBLIC_V5_IMMERSIVE_RUN=true\nObserved: false\nContext: production Worker version ...',
  }),
  prompt({
    name: 'DATABASE_LOCK_BLOCKING_ANALYZER',
    displayTitle: 'Database Lock & Blocking Analyzer',
    displayTitleTh: 'วิเคราะห์ Database Lock และ Blocking',
    description: 'Analyze lock, blocker/waiter, transaction, and query evidence to isolate database blocking.',
    descriptionTh: 'วิเคราะห์ Lock, blocker/waiter, transaction และ query evidence เพื่อหาสาเหตุของ Database blocking',
    category: 'Database',
    variables: ['database_engine', 'lock_evidence', 'queries', 'symptoms'],
    tags: ['DATABASE', 'LOCK', 'BLOCKING', 'TRANSACTION'],
    collections: ['Developer Toolkit', 'Data & Analysis'],
    outputFormat: 'Database blocking diagnostic report',
    prompt: `# Role\nYou are a senior database reliability engineer.\n\n# Inputs\nDatabase engine/version: {{database_engine}}\nLock evidence: {{lock_evidence}}\nQueries/transactions: {{queries}}\nSymptoms: {{symptoms}}\n\n# Method\nIdentify blocker/waiter chains only from supplied evidence, transaction scope, lock modes/resources, long-running transactions, and query-order/deadlock clues. Do not recommend killing a session unless the operational risk and evidence are explicit.\n\n# Output\n- Observed lock/blocking chain\n- Affected queries/transactions\n- Likely cause\n- Data still needed\n- Safe immediate checks\n- Remediation options and risks\n- Prevention ideas`,
    purposeTh: 'ใช้ไล่ session/transaction ที่ block กันในฐานข้อมูลจาก lock evidence จริง โดยแยกการตรวจสอบออกจาก action เสี่ยงอย่าง terminate session',
    useCasesTh: ['Query รอ lock', 'Transaction ค้างนาน', 'Deadlock/blocking incident'],
    inputGuideTh: { database_engine: 'ระบุ PostgreSQL/MySQL/SQL Server และ version ถ้าทราบ', lock_evidence: 'วาง lock/wait/session output', queries: 'วาง query/transaction ที่เกี่ยวข้อง', symptoms: 'อธิบาย latency, timeout หรือ workload impact' },
    expectedOutputTh: ['Blocker/waiter chain', 'Likely cause และ missing evidence', 'Safe checks/remediation risks'],
    exampleInputTh: 'DB: PostgreSQL 17\nSymptoms: update orders timeout\nLock evidence: pid 120 waits for transaction held by pid 98 ...',
  }),
  prompt({
    name: 'CSV_EXCEL_DATA_QUALITY_ANALYZER',
    displayTitle: 'CSV / Excel Data Quality Analyzer',
    displayTitleTh: 'วิเคราะห์คุณภาพข้อมูล CSV / Excel',
    description: 'Assess tabular data quality from supplied schema/sample evidence, including grain, missingness, duplicates, ranges, and join risks.',
    descriptionTh: 'ตรวจคุณภาพข้อมูลตารางจาก schema/sample โดยดู grain, missingness, duplicate, type/range และความเสี่ยงในการ join',
    category: 'Data Analysis',
    variables: ['data_description', 'sample_data', 'goal'],
    tags: ['CSV', 'EXCEL', 'DATA_QUALITY', 'ANALYSIS'],
    collections: ['Data & Analysis', 'Popular AI Prompts'],
    outputFormat: 'Data-quality assessment and validation plan',
    prompt: `# Role\nYou are a senior data-quality analyst.\n\n# Inputs\nDataset description: {{data_description}}\nSample/schema/data profile: {{sample_data}}\nAnalysis goal: {{goal}}\n\n# Analyze only what the supplied sample/profile can support\n- intended grain/key\n- missingness/null semantics\n- duplicates/near duplicates\n- type/format/range/domain issues\n- date/time/unit consistency\n- referential/join-key risks\n- freshness/coverage when evidence exists\n\n# Output\n- Dataset/grain interpretation\n- Verified quality findings\n- Risks that need full-data checks\n- Validation rules/queries to run\n- Priority fixes\n- Fitness for the stated goal: demonstrated / uncertain / unsuitable`,
    purposeTh: 'ใช้ตรวจว่าข้อมูล CSV/Excel พร้อมสำหรับ analysis หรือไม่จากตัวอย่าง/schema ที่มี โดยไม่สรุปคุณภาพทั้ง dataset เกินหลักฐาน',
    useCasesTh: ['ตรวจไฟล์ก่อนวิเคราะห์', 'หา missing/duplicate/type issues', 'ตรวจ key/join risk ก่อนรวมหลายชีต'],
    inputGuideTh: { data_description: 'อธิบายแหล่งข้อมูล ความหมายของหนึ่งแถว และ columns สำคัญ', sample_data: 'วาง sample rows/schema/profile summary โดยตัดข้อมูลส่วนบุคคลที่ไม่จำเป็น', goal: 'ระบุว่าจะนำข้อมูลไปทำอะไร เช่น KPI, import, model' },
    expectedOutputTh: ['Grain/key assessment', 'Verified findings vs full-data checks', 'Validation rules และ priority fixes'],
    exampleInputTh: 'Description: Ticket export หนึ่งแถวต่อ ticket\nSample: ticket_id, created_at, resolved_at, site...\nGoal: วิเคราะห์ SLA ราย site',
  }),
  prompt({
    name: 'FUNNEL_DROP_OFF_ANALYZER',
    displayTitle: 'Funnel Drop-off Analyzer',
    displayTitleTh: 'วิเคราะห์ Funnel Drop-off',
    description: 'Analyze conversion funnel stages and supplied segment data to isolate where drop-off changes and what evidence is still needed.',
    descriptionTh: 'วิเคราะห์แต่ละขั้นของ Conversion Funnel และ segment data เพื่อหาว่า drop-off เปลี่ยนที่จุดใดและมี driver อะไรที่หลักฐานรองรับ',
    category: 'Data Analysis',
    variables: ['funnel_definition', 'funnel_data', 'context'],
    tags: ['FUNNEL', 'CONVERSION', 'PRODUCT_ANALYTICS', 'ROOT_CAUSE'],
    collections: ['Data & Analysis'],
    outputFormat: 'Funnel and segment diagnostic analysis',
    prompt: `# Role\nYou are a product analytics investigator.\n\n# Inputs\nFunnel definition: {{funnel_definition}}\nFunnel/segment data: {{funnel_data}}\nContext/recent changes: {{context}}\n\n# Method\nVerify stage definitions/denominators, compute or use supplied conversion/drop-off only when data permits, compare periods/segments, distinguish mix shift from within-segment change, and keep product-change hypotheses separate from measured evidence.\n\n# Output\n- Funnel definition/data checks\n- Largest verified drop-off changes\n- Segment decomposition\n- Evidence-backed drivers\n- Hypotheses needing validation\n- Next queries/experiments`,
    purposeTh: 'ใช้หา funnel stage ที่แย่ลงจริง พร้อมแยก segment mix, denominator และ product-change hypothesis เพื่อไม่สรุป root cause จาก aggregate เพียงตัวเดียว',
    useCasesTh: ['Signup/checkout conversion ลด', 'หา drop-off ตาม device/channel/region', 'ตรวจผลหลัง product release'],
    inputGuideTh: { funnel_definition: 'ระบุ stage และเงื่อนไขนับแต่ละขั้น', funnel_data: 'วาง counts/rates แยกเวลาและ segment ที่มี', context: 'ระบุ release, campaign หรือเหตุการณ์ที่อาจเกี่ยวข้องโดยไม่สรุปว่าเป็นสาเหตุ' },
    expectedOutputTh: ['Verified funnel movement', 'Segment decomposition', 'Driver evidence vs hypotheses และ next analysis'],
    exampleInputTh: 'Funnel: visit → add_to_cart → checkout → paid\nData: weekly counts by iOS/Android/Web\nContext: checkout redesign deployed Sep 20',
  }),
  prompt({
    name: 'EVIDENCE_GAP_ASSUMPTION_AUDITOR',
    displayTitle: 'Evidence Gap & Assumption Auditor',
    displayTitleTh: 'ตรวจช่องว่างหลักฐานและสมมติฐาน',
    description: 'Audit a decision, proposal, or argument for unsupported assumptions, evidence gaps, and verification priorities.',
    descriptionTh: 'ตรวจ proposal/decision/argument เพื่อหา assumption ที่ซ่อนอยู่ ช่องว่างหลักฐาน และสิ่งที่ต้อง verify ก่อนตัดสินใจ',
    category: 'Decision Support',
    variables: ['decision_or_claim', 'evidence', 'constraints'],
    tags: ['EVIDENCE', 'ASSUMPTION', 'DECISION', 'AUDIT'],
    collections: ['Research Toolkit', 'Productivity'],
    outputFormat: 'Evidence-gap and assumption audit',
    prompt: `# Role\nYou are an evidence and decision-quality auditor.\n\n# Inputs\nDecision / claim / proposal: {{decision_or_claim}}\nEvidence supplied: {{evidence}}\nConstraints: {{constraints}}\n\n# Method\nDecompose conclusions into premises, map each premise to supplied evidence, identify hidden assumptions, distinguish unknown from unsupported, and rank gaps by how much they could change the decision.\n\n# Output\n- Decision/claim decomposition\n- Evidence-backed premises\n- Unsupported/weak premises\n- Hidden assumptions\n- High-impact unknowns\n- Verification priorities\n- What can and cannot be concluded now`,
    purposeTh: 'ใช้ตรวจคุณภาพเหตุผลก่อนตัดสินใจ โดยไม่ได้ทำซ้ำ fact checker แต่เน้นว่า conclusion ต้องพึ่ง assumption/unknown อะไรและ gap ไหนมีผลสูงสุด',
    useCasesTh: ['Review business proposal', 'ตรวจ technical decision', 'เตรียมคำถามก่อนอนุมัติโครงการ'],
    inputGuideTh: { decision_or_claim: 'วางข้อเสนอหรือข้อสรุปที่กำลังจะใช้ตัดสินใจ', evidence: 'วางข้อมูล/หลักฐานที่มีจริง', constraints: 'ระบุ budget/time/policy หรือข้อจำกัดที่มีผล' },
    expectedOutputTh: ['Evidence-to-premise mapping', 'Hidden assumptions/gaps', 'Verification priorities และ conclusion boundary'],
    exampleInputTh: 'Decision: ย้าย monitoring ทั้งหมดไป tool B เพราะ “ถูกกว่าและครอบคลุมกว่า”\nEvidence: ราคา quote + feature list\nConstraints: 3 sites, migration 2 weeks',
  }),
  prompt({
    name: 'REQUIREMENTS_TRADE_OFF_ANALYZER',
    displayTitle: 'Requirements Trade-off Analyzer',
    displayTitleTh: 'วิเคราะห์ Trade-off ของ Requirements และตัวเลือก',
    description: 'Compare options against explicit requirements, constraints, and evidence without inventing a winner.',
    descriptionTh: 'เปรียบเทียบตัวเลือกตาม requirement, constraints และ evidence ที่กำหนด โดยไม่แต่งคะแนนหรือเลือกผู้ชนะเมื่อข้อมูลไม่พอ',
    category: 'Decision Support',
    variables: ['options', 'requirements', 'constraints', 'evidence'],
    tags: ['TRADE_OFF', 'REQUIREMENTS', 'DECISION', 'COMPARISON'],
    collections: ['Productivity'],
    outputFormat: 'Requirement-by-option trade-off matrix',
    prompt: `# Role\nYou are a requirements and trade-off analyst.\n\n# Inputs\nOptions: {{options}}\nRequirements: {{requirements}}\nConstraints: {{constraints}}\nEvidence: {{evidence}}\n\n# Rules\nDo not invent scores, prices, capabilities, or priorities. If requirement weights are not provided, compare without weighting.\n\n# Output\n- Normalized requirements\n- Option × requirement evidence matrix\n- Conflicts/dependencies\n- Trade-offs\n- Unknowns that block a fair comparison\n- Decision implications; state when no winner can be supported`,
    purposeTh: 'ใช้เปรียบเทียบหลายทางเลือกอย่าง traceable ตาม requirement จริง โดยแสดง unknowns และ trade-offs แทนการสร้างคะแนนปลอมเพื่อบังคับ winner',
    useCasesTh: ['เลือก vendor/tool', 'เปรียบเทียบ architecture', 'ตัด scope เมื่อ requirements ขัดกัน'],
    inputGuideTh: { options: 'ระบุตัวเลือกและข้อมูลที่ทราบของแต่ละตัว', requirements: 'ระบุ must-have / nice-to-have หรือ requirement list', constraints: 'ระบุ budget/time/platform/policy constraints', evidence: 'วาง source data หรือข้อมูลยืนยันของแต่ละ option' },
    expectedOutputTh: ['Option × requirement matrix', 'Trade-offs/conflicts', 'Unknowns และ decision implications'],
    exampleInputTh: 'Options: Tool A, B, C\nRequirements: SNMP, Syslog, SSO, mobile alerts\nConstraints: budget 50k/year\nEvidence: vendor docs/quotes',
  }),
  prompt({
    name: 'INCIDENT_TIMELINE_RECONSTRUCTOR',
    displayTitle: 'Incident Timeline Reconstructor',
    displayTitleTh: 'สร้าง Timeline เหตุการณ์จาก Log หลายแหล่ง',
    description: 'Reconstruct a normalized incident timeline from logs, alerts, tickets, and notes while handling clock uncertainty.',
    descriptionTh: 'รวม Log, Alert, Ticket และ Notes หลายแหล่งเป็น Incident Timeline พร้อมจัดการ timezone/clock skew และความไม่แน่นอน',
    category: 'Productivity',
    variables: ['events', 'time_context', 'incident_goal'],
    tags: ['INCIDENT', 'TIMELINE', 'LOGS', 'FORENSICS'],
    collections: ['Developer Toolkit', 'Productivity'],
    outputFormat: 'Normalized incident timeline and evidence gaps',
    prompt: `# Role\nYou are an incident analyst reconstructing chronology.\n\n# Inputs\nEvents/logs/notes: {{events}}\nTime context/time zones/known clock issues: {{time_context}}\nIncident goal: {{incident_goal}}\n\n# Method\nPreserve original timestamps and sources, normalize time only when timezone/offset is known, identify duplicates/correlated events, flag uncertain ordering caused by clock skew, and never create events that are not supplied.\n\n# Output\n- Normalization assumptions\n- Chronological timeline: normalized time | original time | source | event | confidence\n- Key transitions\n- Conflicting timestamps/clock uncertainty\n- Missing intervals/evidence\n- Questions for follow-up`,
    purposeTh: 'ใช้รวมเหตุการณ์จากหลายระบบให้เป็น timeline เดียวโดยไม่เสีย timestamp ต้นฉบับ และชี้จุดที่ลำดับเวลาไม่แน่นอนจาก timezone/clock skew',
    useCasesTh: ['Reconstruct outage chronology', 'รวม NOC/SOC/app logs', 'เตรียม evidence ก่อน postmortem'],
    inputGuideTh: { events: 'วาง events พร้อม timestamp และ source ให้มากที่สุด', time_context: 'ระบุ timezone ของแต่ละ source หรือ clock skew ที่ทราบ', incident_goal: 'ระบุว่าต้องการตอบคำถามอะไรจาก timeline' },
    expectedOutputTh: ['Normalized timeline พร้อม source/confidence', 'Key transitions', 'Timestamp conflicts และ evidence gaps'],
    exampleInputTh: 'Events: 10:01 switch link down, 03:02Z app timeout, ticket 10:05 user report\nTime context: switch/ticket ICT, app UTC',
  }),
  prompt({
    name: 'PROFESSIONAL_MESSAGE_EMAIL_BUILDER',
    displayTitle: 'Professional Message & Email Builder',
    displayTitleTh: 'สร้างข้อความและอีเมลแบบมืออาชีพ',
    description: 'Turn a goal and factual context into a concise, send-ready professional message without inventing details.',
    descriptionTh: 'เปลี่ยนเป้าหมายและข้อมูลจริงให้เป็นข้อความ/อีเมลพร้อมส่ง โดยไม่เติมข้อเท็จจริง ชื่อ วันเวลา หรือ commitment ที่ไม่ได้ให้มา',
    category: 'Productivity',
    variables: ['goal', 'context', 'tone'],
    tags: ['EMAIL', 'MESSAGE', 'WRITING', 'WORK'],
    collections: ['Productivity', 'Popular AI Prompts'],
    outputFormat: 'Send-ready professional draft',
    prompt: `# Role\nYou are a professional workplace communication editor.\n\n# Inputs\nGoal: {{goal}}\nFactual context: {{context}}\nTone: {{tone}}\n\n# Rules\nUse only supplied facts. Do not invent names, dates, deadlines, promises, causes, or attachments. Preserve technical names/numbers accurately.\n\n# Output\nProduce one send-ready draft appropriate to the requested goal and tone. If it is clearly an email, include a concise subject suggestion before the body. If essential recipient/context information is missing, use neutral wording rather than placeholders that look factual.`,
    purposeTh: 'ใช้ร่างอีเมลหรือข้อความงานจาก facts ที่ผู้ใช้ให้ เหมาะกับงานแจ้ง incident, follow-up, ขอข้อมูล หรืออัปเดตสถานะ โดยไม่สร้างรายละเอียดที่ไม่มี',
    useCasesTh: ['แจ้ง incident/status', 'Follow-up งาน', 'ขอข้อมูลหรือขออนุมัติอย่างสุภาพ'],
    inputGuideTh: { goal: 'ระบุว่าต้องการให้ผู้รับทำ/เข้าใจอะไร', context: 'วาง facts ที่ต้องมีในข้อความ เช่น ticket, status, เวลา, technical detail', tone: 'ระบุโทน เช่น professional, concise, friendly' },
    expectedOutputTh: ['ข้อความพร้อมส่ง', 'Subject suggestion เมื่อเป็นอีเมล', 'ไม่มี facts ที่ผู้ใช้ไม่ได้ให้'],
    exampleInputTh: 'Goal: แจ้งผู้ใช้ว่า network กลับมาใช้งานได้และขอให้ทดสอบ\nContext: INC-1052, service restored 10:45, monitoring normal\nTone: Professional concise',
  }),
  prompt({
    name: 'TRAVEL_RESEARCH_PLANNER',
    displayTitle: 'Travel Research Planner',
    displayTitleTh: 'วางแผน Research ก่อนจัดทริป',
    description: 'Structure destination research, constraints, verification needs, and decision points before building an itinerary.',
    descriptionTh: 'จัดกรอบค้นคว้าสถานที่ เวลาเดินทาง ค่าใช้จ่าย และข้อจำกัดก่อนนำข้อมูลจริงไปสร้าง itinerary',
    category: 'Travel',
    variables: ['destination', 'dates', 'preferences', 'constraints'],
    tags: ['TRAVEL', 'RESEARCH', 'PLANNING', 'ITINERARY'],
    collections: ['Productivity'],
    outputFormat: 'Travel research checklist and itinerary framework',
    prompt: `# Role\nYou are a travel research planner.\n\n# Inputs\nDestination: {{destination}}\nDates: {{dates}}\nPreferences: {{preferences}}\nConstraints: {{constraints}}\n\n# Rules\nDo not invent current opening hours, prices, weather, closures, transport schedules, or availability. Identify which facts require live verification.\n\n# Output\n- Trip goals/profile\n- Research categories and questions\n- Candidate-area framework (without fabricated places if none were supplied)\n- Logistics/transport checks\n- Budget inputs to collect\n- Live facts to verify\n- Itinerary framework by day/area\n- Decision checklist`,
    purposeTh: 'ใช้จัดโจทย์ research ทริปก่อนค้นข้อมูลจริง โดยระบุสิ่งที่ต้อง verify แบบสด เช่น เวลาเปิด ราคา สภาพอากาศ การปิดพื้นที่ และการเดินทาง',
    useCasesTh: ['เริ่มวางทริปจังหวัดใหม่', 'สร้าง checklist ก่อนค้น TikTok/Maps/Web', 'จัด constraints ก่อนทำ itinerary'],
    inputGuideTh: { destination: 'ระบุจังหวัด/เมือง/ประเทศหรือหลายจุดหมาย', dates: 'ระบุวันเดินทางหรือช่วงเวลา', preferences: 'ระบุประเภทที่เที่ยว กิจกรรม อาหาร pace และสิ่งที่ชอบ', constraints: 'ระบุ budget, รถ/ขนส่ง, เวลา, ที่พัก, ผู้ร่วมทริป หรือสิ่งที่ต้องเลี่ยง' },
    expectedOutputTh: ['Research checklist', 'Live facts ที่ต้อง verify', 'Itinerary framework และ decision points'],
    exampleInputTh: 'Destination: จันทบุรี\nDates: 17–19 Oct 2026\nPreferences: ธรรมชาติ กิจกรรม Unseen คาเฟ่น้อย\nConstraints: ขับรถเอง งบที่พักไม่เกิน 1,500/คืน',
  }),
  prompt({
    name: 'PUBLIC_COMPANY_RESEARCH_BRIEF',
    displayTitle: 'Public Company Research Brief',
    displayTitleTh: 'สรุป Research บริษัทจดทะเบียนจาก Sources ที่ให้มา',
    description: 'Build a source-grounded public-company research brief covering business, financial evidence, catalysts, risks, and uncertainty.',
    descriptionTh: 'สร้าง Research Brief บริษัทจดทะเบียนจาก sources ที่ผู้ใช้ให้ โดยแยก business/financial facts, catalysts, risks และ uncertainty',
    category: 'Finance',
    variables: ['company', 'research_goal', 'sources'],
    tags: ['EQUITY_RESEARCH', 'COMPANY', 'FINANCE', 'SOURCES'],
    collections: ['Data & Analysis'],
    outputFormat: 'Source-grounded company research brief',
    prompt: `# Role\nYou are a public-company research analyst working only from supplied sources.\n\n# Inputs\nCompany/security: {{company}}\nResearch goal: {{research_goal}}\nSources/data: {{sources}}\n\n# Rules\nDo not fabricate current prices, filings, earnings, estimates, dates, catalysts, or financial metrics. Cite source labels/URLs supplied by the user when attributing facts. Separate facts, calculations, interpretation, and uncertainty. Do not provide personalized buy/sell instructions.\n\n# Output\n- Company/business snapshot\n- Financial/operating facts from sources\n- Recent developments represented in supplied sources\n- Potential catalysts and risks, clearly labeled as sourced facts vs interpretation\n- Key metrics/evidence table\n- Conflicting/missing information\n- Questions to verify next\n- Concise research conclusion, not a personalized recommendation`,
    purposeTh: 'ใช้สรุปบริษัทมหาชนจาก filing/news/data ที่แนบมาอย่าง traceable โดยไม่อ้างข้อมูล “ล่าสุด” ที่ไม่ได้ให้ และไม่เปลี่ยนเป็นคำสั่งซื้อ/ขายส่วนบุคคล',
    useCasesTh: ['สรุป earnings/filing ที่แนบมา', 'เตรียม company brief', 'เทียบ catalysts/risks จากหลาย source'],
    inputGuideTh: { company: 'ระบุชื่อบริษัท/ticker/security', research_goal: 'ระบุคำถาม เช่น รายได้ margin debt catalyst หรือ thesis check', sources: 'วาง filing, earnings text, article, table หรือ URL/text ที่ต้องการใช้เป็น evidence' },
    expectedOutputTh: ['Business/financial facts', 'Catalysts/risks แยก fact vs interpretation', 'Missing/conflicting evidence และ next verification'],
    exampleInputTh: 'Company: CCL\nResearch goal: ตรวจแนวโน้ม demand, margin และ debt จาก earnings materials\nSources: earnings release excerpts + filing links ...',
  }),
  prompt({
    name: 'CERTIFICATION_READINESS_GAP_ANALYZER',
    displayTitle: 'Certification Readiness Gap Analyzer',
    displayTitleTh: 'วิเคราะห์ช่องว่างความพร้อมก่อนสอบ Certification',
    description: 'Assess current knowledge evidence against a certification blueprint and prioritize readiness gaps without replacing the existing study-plan prompt.',
    descriptionTh: 'วิเคราะห์ความพร้อมจาก blueprint และหลักฐานการทำโจทย์/แลบ เพื่อหา topic gap ก่อนสอบ โดยเน้น assessment ไม่ใช่สร้าง study plan ทั่วไป',
    category: 'Education',
    variables: ['certification', 'blueprint_or_topics', 'current_evidence', 'exam_date'],
    tags: ['CERTIFICATION', 'READINESS', 'GAP_ANALYSIS', 'LEARNING'],
    collections: ['Learning'],
    outputFormat: 'Certification readiness gap assessment',
    prompt: `# Role\nYou are a certification readiness assessor.\n\n# Inputs\nCertification: {{certification}}\nBlueprint/topics: {{blueprint_or_topics}}\nCurrent evidence: {{current_evidence}}\nExam date: {{exam_date}}\n\n# Rules\nJudge readiness only from supplied evidence such as practice results, labs, questions missed, or demonstrated skills. Do not claim official exam weighting unless supplied in the blueprint.\n\n# Output\n- Evidence summary\n- Topic-by-topic readiness: demonstrated / partial / not demonstrated\n- Highest-risk gaps\n- Practical verification labs/questions\n- Priority order before exam\n- Readiness conclusion with uncertainty`,
    purposeTh: 'ใช้ประเมินว่าหัวข้อใด “ทำได้จริงแล้ว/ยังไม่แน่น/ยังไม่มีหลักฐาน” จาก blueprint และผล practice/lab เพื่อเลือกจุดที่ต้องปิด gap ก่อนสอบ',
    useCasesTh: ['ประเมิน CCNA/CCNP/Security+ ก่อนสอบ', 'วิเคราะห์ผล mock exam', 'เลือกหัวข้อ lab ที่ควรทดสอบซ้ำ'],
    inputGuideTh: { certification: 'ระบุชื่อ certification/version ถ้าทราบ', blueprint_or_topics: 'วาง official blueprint หรือ topic list ที่ใช้เป็นกรอบ', current_evidence: 'วาง mock scores, ข้อที่พลาด, lab ที่ทำได้/ไม่ได้ หรือ notes', exam_date: 'ระบุวันสอบหรือเวลาที่เหลือ' },
    expectedOutputTh: ['Topic readiness matrix', 'Highest-risk gaps', 'Verification exercises และ readiness conclusion'],
    exampleInputTh: 'Certification: CCNA 200-301\nTopics: network fundamentals, access, IP connectivity...\nEvidence: mock 72%, พลาด OSPF/STP/ACL, ทำ VLAN lab ได้\nExam date: 2026-12-15',
  }),
]);

export const NEW_PROMPT_QUALITY_METADATA = Object.freeze(Object.fromEntries(
  NEW_QUALITY_PROMPT_SPECS.map((spec) => [spec.name, Object.freeze({
    descriptionTh: spec.descriptionTh,
    purposeTh: spec.purposeTh,
    useCasesTh: Object.freeze([...(spec.useCasesTh || [])]),
    inputGuideTh: Object.freeze({ ...(spec.inputGuideTh || {}) }),
    expectedOutputTh: Object.freeze([...(spec.expectedOutputTh || [])]),
    exampleInputTh: spec.exampleInputTh,
  })]),
));
