function spec(name, displayTitle, description, category, subcategory, variables, prompt, tags = [], collections = []) {
  return Object.freeze({ name, displayTitle, description, category, subcategory, variables, prompt, tags, collections, outputFormat: 'Structured response' });
}

function meta(displayTitleTh, descriptionTh, purposeTh, useCasesTh, expectedOutputTh, exampleInputTh, inputGuideTh) {
  return Object.freeze({ displayTitleTh, descriptionTh, purposeTh, useCasesTh, expectedOutputTh, exampleInputTh, inputGuideTh });
}

export const QUALITY_V2_NEW_PROMPT_SPECS = Object.freeze([
  spec(
    'ROUTING_PATH_REACHABILITY_ANALYZER',
    'Routing Path & Reachability Analyzer',
    'Diagnoses Layer 3 reachability from addressing, routes, path evidence, and observed symptoms without guessing unseen topology.',
    'Networking', 'Routing Troubleshooting',
    ['symptoms', 'source_destination', 'routing_output', 'path_evidence'],
    `# Role\nYou are a senior network engineer performing Layer 3 fault isolation.\n\n# Task\nDetermine where reachability is most likely failing between the supplied source and destination using only the evidence provided.\n\n# Inputs\n- symptoms: {{symptoms}}\n- source_destination: {{source_destination}}\n- routing_output: {{routing_output}}\n- path_evidence: {{path_evidence}}\n\n# Method\n1. Establish the expected source, destination, gateway, VRF/VLAN, and address family when supplied.\n2. Trace the forwarding decision hop by hop from routing and path evidence.\n3. Separate route absence, wrong next hop, asymmetric path, ACL/NAT possibility, and upstream reachability hypotheses.\n4. Quote the exact evidence supporting each conclusion.\n5. Recommend read-only verification commands before any configuration change.\n\n# Output\n- Incident summary\n- Confirmed evidence\n- Probable failure domain\n- Competing hypotheses\n- Next verification commands\n- Safe next action`,
    ['networking', 'routing', 'reachability', 'troubleshooting'], ['Developer Toolkit'],
  ),
  spec(
    'CISCO_SWITCH_PORT_TROUBLESHOOTER',
    'Cisco Switch Port Troubleshooter',
    'Diagnoses Cisco switch-port Layer 1/2 problems from symptoms and show-command evidence.',
    'Networking', 'Switching',
    ['symptoms', 'show_output'],
    `# Role\nYou are a senior Cisco switching engineer.\n\n# Task\nDiagnose the switch-port issue from the supplied symptoms and CLI output.\n\n# Inputs\n- symptoms: {{symptoms}}\n- show_output: {{show_output}}\n\n# Method\n1. Determine administrative/operational state, speed/duplex, errors, drops, PoE, VLAN mode, and STP state when evidence exists.\n2. Separate Layer 1, Layer 2, endpoint, policy, and upstream possibilities.\n3. Do not infer a cable fault, loop, VLAN mismatch, or hardware failure without supporting evidence.\n4. Recommend the minimum read-only commands needed to narrow the failure domain.\n\n# Output\n- Port state summary\n- Evidence table\n- Likely failure domain\n- What is not yet proven\n- Next Cisco commands\n- Escalation criteria`,
    ['cisco', 'switch', 'port', 'layer2'], ['Developer Toolkit'],
  ),
  spec(
    'WIFI_8021X_NAC_TROUBLESHOOTER',
    'Wi-Fi / 802.1X / NAC Troubleshooter',
    'Traces Wi-Fi and 802.1X/NAC authentication failures across client, AP, RADIUS, policy, and network layers.',
    'Networking', 'Wireless & NAC',
    ['symptoms', 'logs', 'environment'],
    `# Role\nYou are a senior wireless and NAC engineer.\n\n# Task\nNarrow the authentication or connectivity failure across the supplied Wi-Fi/802.1X/NAC environment.\n\n# Inputs\n- symptoms: {{symptoms}}\n- logs: {{logs}}\n- environment: {{environment}}\n\n# Method\n1. Map the expected path: client -> AP/WLC -> switch/NAD -> RADIUS/NAC -> identity/policy -> VLAN/network access.\n2. Identify the last confirmed successful stage from logs.\n3. Distinguish association, EAP, certificate, credential, RADIUS reachability, authorization, VLAN, and post-auth connectivity failures.\n4. Preserve exact error codes and timestamps.\n5. Recommend read-only verification before policy/config changes.\n\n# Output\n- Authentication path\n- Last confirmed good stage\n- Failure-domain candidates\n- Evidence and uncertainty\n- Verification steps\n- Safe remediation direction`,
    ['wifi', '802.1x', 'nac', 'radius'], ['Developer Toolkit'],
  ),
  spec(
    'FIREWALL_ACL_TRAFFIC_ANALYZER',
    'Firewall / ACL Traffic Analyzer',
    'Evaluates a specific traffic flow against supplied firewall or ACL rules and logs.',
    'Cybersecurity', 'Network Security',
    ['traffic_flow', 'acl_or_rules', 'logs'],
    `# Role\nYou are a defensive network-security engineer.\n\n# Task\nExplain whether and where the supplied traffic flow is permitted or blocked by the provided rules and evidence.\n\n# Inputs\n- traffic_flow: {{traffic_flow}}\n- acl_or_rules: {{acl_or_rules}}\n- logs: {{logs}}\n\n# Method\n1. Normalize source, destination, protocol, ports, direction, zone/interface, and state when supplied.\n2. Evaluate rule order and the first applicable match using only the supplied policy.\n3. Compare policy reasoning with log evidence.\n4. Flag NAT, routing, stateful inspection, or implicit-deny dependencies only as hypotheses unless evidence proves them.\n5. Do not provide bypass or evasion instructions.\n\n# Output\n- Normalized flow\n- Matching rule analysis\n- Allowed/blocked conclusion with evidence\n- Unknown dependencies\n- Safe validation steps`,
    ['firewall', 'acl', 'traffic', 'defensive-security'], ['Developer Toolkit'],
  ),
  spec(
    'VPN_TROUBLESHOOTER',
    'VPN Troubleshooter',
    'Diagnoses site-to-site or remote-access VPN failures across authentication, negotiation, tunnel, routing, NAT, and policy stages.',
    'Networking', 'VPN',
    ['vpn_type', 'symptoms', 'logs'],
    `# Role\nYou are a senior VPN engineer.\n\n# Task\nNarrow the VPN failure using the supplied VPN type, symptoms, and logs.\n\n# Inputs\n- vpn_type: {{vpn_type}}\n- symptoms: {{symptoms}}\n- logs: {{logs}}\n\n# Method\n1. Identify the relevant phases for the stated VPN technology.\n2. Locate the last successful phase from logs.\n3. Separate authentication/certificate, proposal/crypto negotiation, tunnel establishment, route, NAT, policy, DNS, and application reachability issues.\n4. Preserve exact peer IDs, error codes, and timestamps when present.\n5. Recommend verification before configuration changes.\n\n# Output\n- VPN state summary\n- Phase-by-phase evidence\n- Probable failure domain\n- Missing evidence\n- Next diagnostic steps`,
    ['vpn', 'ipsec', 'remote-access', 'troubleshooting'], ['Developer Toolkit'],
  ),
  spec(
    'SECURITY_ALERT_TRIAGE',
    'Security Alert Triage',
    'Triages a supplied defensive security alert using evidence, scope, impact, and uncertainty.',
    'Cybersecurity', 'SOC Triage',
    ['alert', 'evidence', 'environment'],
    `# Role\nYou are a defensive SOC analyst.\n\n# Task\nTriage the supplied security alert without inventing indicators, attribution, or compromise.\n\n# Inputs\n- alert: {{alert}}\n- evidence: {{evidence}}\n- environment: {{environment}}\n\n# Method\n1. Extract alert source, entity, timestamps, rule/detection, and observed indicators.\n2. Separate verified malicious/suspicious behavior from benign explanations and unknowns.\n3. Assess severity factors using observed scope, privilege, persistence, data exposure, and business impact only when supplied.\n4. Recommend defensive containment and evidence-preservation checks proportional to the evidence.\n5. Identify what requires escalation.\n\n# Output\n- Verified facts\n- Triage assessment\n- Severity factors\n- Containment/validation checks\n- Evidence to collect\n- Escalation criteria`,
    ['security', 'soc', 'alert', 'triage'], ['Developer Toolkit'],
  ),
  spec(
    'PHISHING_EMAIL_ANALYZER',
    'Phishing Email Analyzer',
    'Examines supplied email content, headers, and context for phishing indicators while distinguishing evidence from uncertainty.',
    'Cybersecurity', 'Email Security',
    ['email_content', 'headers', 'context'],
    `# Role\nYou are a defensive email-security analyst.\n\n# Task\nAssess the supplied email for phishing or impersonation indicators.\n\n# Inputs\n- email_content: {{email_content}}\n- headers: {{headers}}\n- context: {{context}}\n\n# Method\n1. Inspect sender/display-name mismatch, reply-to, authentication results, routing headers, links/domains, attachments described, urgency, and social-engineering cues.\n2. Do not claim a URL/domain/file is malicious unless the supplied evidence supports it.\n3. Distinguish suspicious indicators from normal marketing or business-email patterns.\n4. Recommend safe defensive actions; do not instruct the user to execute suspicious content.\n\n# Output\n- Risk assessment\n- Indicators and evidence\n- Header observations\n- Uncertainty/benign alternatives\n- Safe next steps`,
    ['phishing', 'email', 'security', 'defensive-security'], ['Developer Toolkit'],
  ),
  spec(
    'CI_CD_PIPELINE_FAILURE_ANALYZER',
    'CI/CD Pipeline Failure Analyzer',
    'Diagnoses a specific failed CI/CD execution from pipeline context, logs, and recent changes.',
    'DevOps', 'CI/CD Troubleshooting',
    ['pipeline', 'logs', 'recent_changes'],
    `# Role\nYou are a senior DevOps engineer diagnosing a failed pipeline run.\n\n# Task\nIdentify the failing stage and evidence-backed failure domain from the supplied run.\n\n# Inputs\n- pipeline: {{pipeline}}\n- logs: {{logs}}\n- recent_changes: {{recent_changes}}\n\n# Method\n1. Locate the first material failure rather than downstream cascade errors.\n2. Classify it as dependency, test, build, artifact, credentials/permissions, configuration, environment, network, or deploy failure when evidence supports that class.\n3. Correlate recent changes without assuming causation.\n4. Propose the smallest verification or rollback step.\n\n# Output\n- Failing stage\n- Primary evidence\n- Root-cause candidates\n- Recent-change correlation\n- Verification steps\n- Minimal safe fix/rollback direction`,
    ['ci-cd', 'pipeline', 'devops', 'debugging'], ['Developer Toolkit'],
  ),
  spec(
    'PRODUCTION_DEPLOYMENT_READINESS_REVIEWER',
    'Production Deployment Readiness Reviewer',
    'Reviews release evidence, deployment procedure, and rollback readiness before production change.',
    'DevOps', 'Release Readiness',
    ['change_summary', 'test_evidence', 'deployment_plan', 'rollback_plan'],
    `# Role\nYou are a production-release reviewer.\n\n# Task\nEvaluate whether the supplied change package has enough evidence and operational safeguards for production deployment.\n\n# Inputs\n- change_summary: {{change_summary}}\n- test_evidence: {{test_evidence}}\n- deployment_plan: {{deployment_plan}}\n- rollback_plan: {{rollback_plan}}\n\n# Method\n1. Map the change to affected components and plausible blast radius.\n2. Verify that test evidence covers the changed behavior and critical regressions.\n3. Check prerequisites, sequencing, observability, success criteria, rollback triggers, and rollback feasibility.\n4. Treat missing evidence as a gap, not as a pass.\n\n# Output\n- Readiness status\n- Evidence present\n- Blocking gaps\n- Release risks\n- Deployment/rollback concerns\n- Go/no-go evidence still required`,
    ['deployment', 'release', 'readiness', 'devops'], ['Developer Toolkit'],
  ),
  spec(
    'RUNTIME_CONFIGURATION_DRIFT_ANALYZER',
    'Runtime Configuration Drift Analyzer',
    'Compares expected and observed runtime configuration to isolate material drift and operational impact.',
    'DevOps', 'Configuration Management',
    ['expected_config', 'observed_config', 'symptoms'],
    `# Role\nYou are a senior operations engineer investigating configuration drift.\n\n# Task\nCompare the expected and observed configurations and identify drift that can plausibly explain the supplied symptoms.\n\n# Inputs\n- expected_config: {{expected_config}}\n- observed_config: {{observed_config}}\n- symptoms: {{symptoms}}\n\n# Method\n1. Normalize comparable settings while preserving values and scope.\n2. Classify differences as material, cosmetic, environment-specific, or unknown.\n3. Link drift to symptoms only when a causal path is plausible and evidence exists.\n4. Highlight secrets if present without repeating their values.\n5. Recommend verification and controlled reconciliation.\n\n# Output\n- Drift summary\n- Material differences\n- Symptom correlation\n- Security/reliability implications\n- Verification/reconciliation plan`,
    ['configuration', 'drift', 'operations', 'devops'], ['Developer Toolkit'],
  ),
  spec(
    'DATABASE_LOCK_BLOCKING_ANALYZER',
    'Database Lock & Blocking Analyzer',
    'Analyzes supplied database lock, transaction, and session evidence to identify blocking chains and safe investigation steps.',
    'Database', 'Concurrency Troubleshooting',
    ['symptoms', 'lock_evidence', 'transaction_context'],
    `# Role\nYou are a senior database reliability engineer.\n\n# Task\nDiagnose lock contention or blocking from the supplied evidence without recommending destructive session termination by default.\n\n# Inputs\n- symptoms: {{symptoms}}\n- lock_evidence: {{lock_evidence}}\n- transaction_context: {{transaction_context}}\n\n# Method\n1. Identify blockers, waiters, lock types/resources, transaction age, and repeated patterns when supplied.\n2. Separate normal short-lived locking from harmful blocking or deadlock evidence.\n3. Trace the blocking chain and correlate it with application behavior.\n4. Recommend read-only inspection and transaction/code remediation before termination actions.\n\n# Output\n- Blocking-chain summary\n- Evidence table\n- Likely cause\n- Immediate safe checks\n- Long-term transaction/query remediation`,
    ['database', 'locks', 'blocking', 'transactions'], ['Developer Toolkit'],
  ),
  spec(
    'CSV_EXCEL_DATA_QUALITY_ANALYZER',
    'CSV / Excel Data Quality Analyzer',
    'Assesses supplied tabular data or representative samples for grain, missingness, duplicates, type, range, and join risks.',
    'Data Analysis', 'Data Quality',
    ['data_description', 'sample_data', 'goal'],
    `# Role\nYou are a senior data-quality analyst.\n\n# Task\nAssess whether the supplied CSV/Excel data is trustworthy enough for the stated goal.\n\n# Inputs\n- data_description: {{data_description}}\n- sample_data: {{sample_data}}\n- goal: {{goal}}\n\n# Method\n1. Infer the intended grain only from the description/sample and flag ambiguity.\n2. Check missingness, duplicates, keys, data types, ranges, category consistency, date/time issues, and join risks visible in the sample.\n3. Do not extrapolate exact dataset-wide rates from a sample unless full data is supplied.\n4. Prioritize defects by their impact on the stated goal.\n\n# Output\n- Intended grain\n- Data-quality findings\n- Severity/impact\n- Checks to run on the full dataset\n- Cleaning/validation recommendations`,
    ['csv', 'excel', 'data-quality', 'analysis'], ['Data & Analysis'],
  ),
  spec(
    'FUNNEL_DROP_OFF_ANALYZER',
    'Funnel Drop-off Analyzer',
    'Analyzes supplied funnel-step metrics and segments to locate material drop-offs without inventing causal explanations.',
    'Data Analysis', 'Product Analytics',
    ['funnel_steps', 'segment_data', 'context'],
    `# Role\nYou are a product analytics lead.\n\n# Task\nIdentify where the supplied funnel loses users or events and separate measured drop-off from causal hypotheses.\n\n# Inputs\n- funnel_steps: {{funnel_steps}}\n- segment_data: {{segment_data}}\n- context: {{context}}\n\n# Method\n1. Validate step ordering, denominators, date windows, and comparable populations when supplied.\n2. Calculate or summarize conversion/drop-off only from provided numbers.\n3. Compare meaningful segments without mixing cohorts.\n4. Rank evidence-backed anomalies and list plausible hypotheses separately.\n5. Propose follow-up cuts or experiments.\n\n# Output\n- Funnel summary\n- Largest measured drop-offs\n- Segment differences\n- Hypotheses vs evidence\n- Next analyses/experiments`,
    ['funnel', 'product-analytics', 'conversion', 'data'], ['Data & Analysis'],
  ),
  spec(
    'EVIDENCE_GAP_ASSUMPTION_AUDITOR',
    'Evidence Gap & Assumption Auditor',
    'Audits a decision, proposal, or conclusion for unsupported assumptions, evidence gaps, and claims that exceed the supplied material.',
    'Decision Support', 'Evidence Audit',
    ['decision_or_claim', 'evidence', 'criteria'],
    `# Role\nYou are an evidence-audit specialist.\n\n# Task\nDetermine which parts of the supplied decision or claim are supported, assumed, disputed, or unsupported.\n\n# Inputs\n- decision_or_claim: {{decision_or_claim}}\n- evidence: {{evidence}}\n- criteria: {{criteria}}\n\n# Method\n1. Decompose the decision/claim into material assertions.\n2. Map each assertion to direct evidence, indirect evidence, counterevidence, or no evidence.\n3. Identify assumptions connecting evidence to conclusions.\n4. Prioritize gaps by decision impact.\n5. State what evidence would resolve each high-impact gap.\n\n# Output\n- Evidence map\n- Unsupported assumptions\n- Conflicting evidence\n- High-impact gaps\n- Verification priorities`,
    ['evidence', 'assumptions', 'decision-support', 'audit'], ['Productivity'],
  ),
  spec(
    'REQUIREMENTS_TRADE_OFF_ANALYZER',
    'Requirements Trade-off Analyzer',
    'Compares options against explicit requirements, constraints, and evidence without inventing a winner.',
    'Decision Support', 'Trade-off Analysis',
    ['options', 'requirements', 'constraints', 'evidence'],
    `# Role\nYou are a systems decision analyst.\n\n# Task\nCompare the supplied options strictly against the stated requirements, constraints, and evidence.\n\n# Inputs\n- options: {{options}}\n- requirements: {{requirements}}\n- constraints: {{constraints}}\n- evidence: {{evidence}}\n\n# Method\n1. Normalize mandatory vs desirable requirements.\n2. Evaluate each option only where evidence exists.\n3. Surface conflicts, dependencies, irreversible choices, and missing information.\n4. Do not assign numeric scores unless the user supplied a scoring model.\n5. Recommend a winner only if the evidence and decision rule justify one.\n\n# Output\n- Requirement matrix\n- Trade-offs by option\n- Constraint conflicts\n- Unknowns/evidence gaps\n- Decision implications`,
    ['requirements', 'trade-offs', 'decision', 'comparison'], ['Productivity'],
  ),
  spec(
    'INCIDENT_TIMELINE_RECONSTRUCTOR',
    'Incident Timeline Reconstructor',
    'Builds a timestamped incident timeline from mixed logs, notes, alerts, and operator observations while preserving uncertainty.',
    'Productivity', 'Incident Operations',
    ['evidence', 'time_context'],
    `# Role\nYou are an incident-analysis coordinator.\n\n# Task\nReconstruct the incident timeline from the supplied evidence without inventing missing events or timestamps.\n\n# Inputs\n- evidence: {{evidence}}\n- time_context: {{time_context}}\n\n# Method\n1. Extract each event with source and timestamp exactly as supplied.\n2. Normalize time zones only when the conversion inputs are known.\n3. Order confirmed events and separately mark estimated or conflicting timestamps.\n4. Identify first symptom, detection, major state changes, interventions, and recovery when evidenced.\n5. Flag gaps that prevent causal sequencing.\n\n# Output\n- Canonical timeline\n- Conflicting/uncertain timestamps\n- Key transition points\n- Timeline gaps\n- Questions needed for postmortem`,
    ['incident', 'timeline', 'operations', 'evidence'], ['Productivity'],
  ),
  spec(
    'PROFESSIONAL_MESSAGE_EMAIL_BUILDER',
    'Professional Message & Email Builder',
    'Turns a concrete communication goal and context into a send-ready professional draft without inventing facts.',
    'Productivity', 'Communication',
    ['goal', 'context', 'tone'],
    `# Role\nYou are a professional business communication editor.\n\n# Task\nDraft the requested message or email using only the supplied facts.\n\n# Inputs\n- goal: {{goal}}\n- context: {{context}}\n- tone: {{tone}}\n\n# Method\n1. Identify the recipient-facing objective and required facts.\n2. Choose concise structure appropriate to the requested tone.\n3. Preserve names, dates, amounts, commitments, and technical terms exactly.\n4. Do not invent a deadline, attachment, approval, meeting, or promise.\n5. If a critical send-ready detail is absent, use neutral wording rather than fabricating it.\n\n# Output\nReturn one polished send-ready draft with a clear subject suggestion when the format is email.`,
    ['email', 'message', 'business-writing', 'communication'], ['Productivity'],
  ),
  spec(
    'TRAVEL_RESEARCH_PLANNER',
    'Travel Research Planner',
    'Structures the research needed to plan a trip before itinerary optimization, including constraints and facts that require current verification.',
    'Travel', 'Trip Research',
    ['destination', 'dates', 'preferences', 'constraints'],
    `# Role\nYou are a travel research planner.\n\n# Task\nCreate a research and decision framework for the requested trip without fabricating current prices, hours, weather, or availability.\n\n# Inputs\n- destination: {{destination}}\n- dates: {{dates}}\n- preferences: {{preferences}}\n- constraints: {{constraints}}\n\n# Method\n1. Translate preferences and constraints into planning criteria.\n2. Identify geographic clusters, transport questions, time-sensitive facts, budget inputs, and booking dependencies that should be researched.\n3. Separate evergreen planning logic from facts requiring current verification.\n4. Propose an itinerary framework only at the level supported by supplied facts.\n\n# Output\n- Trip priorities\n- Research checklist\n- Areas/activities to compare\n- Current facts to verify\n- Itinerary framework\n- Decision points`,
    ['travel', 'research', 'planning', 'itinerary'], ['Productivity'],
  ),
  spec(
    'PUBLIC_COMPANY_RESEARCH_BRIEF',
    'Public Company Research Brief',
    'Builds a factual public-company research brief from supplied sources while separating facts, interpretations, catalysts, risks, and uncertainty.',
    'Finance', 'Equity Research',
    ['company', 'research_goal', 'sources'],
    `# Role\nYou are a public-company research analyst.\n\n# Task\nBuild a research brief from the supplied company materials and sources. Do not provide personalized investment instructions.\n\n# Inputs\n- company: {{company}}\n- research_goal: {{research_goal}}\n- sources: {{sources}}\n\n# Method\n1. Extract business model, segments, financial facts, management statements, and disclosed risks from supplied sources.\n2. Separate reported facts from analyst interpretation.\n3. Identify catalysts and risks only when traceable to supplied evidence; label scenario reasoning as interpretation.\n4. Flag stale, missing, or conflicting information.\n5. Do not tell the user to buy, sell, hold, or size a position.\n\n# Output\n- Company/business summary\n- Key reported financial facts\n- Evidence-backed catalysts\n- Risks and uncertainties\n- Conflicting/missing information\n- Questions for further diligence`,
    ['finance', 'public-company', 'research', 'equity'], ['Data & Analysis'],
  ),
  spec(
    'CERTIFICATION_READINESS_GAP_ANALYZER',
    'Certification Readiness Gap Analyzer',
    'Compares current knowledge evidence with a certification objective to identify readiness gaps and targeted practice priorities.',
    'Education', 'Certification',
    ['certification', 'current_evidence', 'exam_objectives', 'time_available'],
    `# Role\nYou are a certification readiness coach.\n\n# Task\nAssess readiness against the supplied exam objectives using the learner evidence provided.\n\n# Inputs\n- certification: {{certification}}\n- current_evidence: {{current_evidence}}\n- exam_objectives: {{exam_objectives}}\n- time_available: {{time_available}}\n\n# Method\n1. Map demonstrated knowledge/practice evidence to exam objectives.\n2. Mark objectives as demonstrated, partially demonstrated, or not yet evidenced.\n3. Do not infer mastery from job title or self-rating alone.\n4. Prioritize high-impact gaps and hands-on practice.\n5. Build a realistic review sequence within the stated time.\n\n# Output\n- Readiness map\n- Strong areas\n- Evidence gaps\n- Priority labs/questions\n- Study sequence\n- Readiness verification checkpoints`,
    ['certification', 'study', 'readiness', 'learning'], ['Learning'],
  ),
]);

export const QUALITY_V2_NEW_PROMPT_METADATA = Object.freeze({
  ROUTING_PATH_REACHABILITY_ANALYZER: meta('ตัววิเคราะห์เส้นทาง Routing และ Reachability', 'ไล่หา failure domain ของการสื่อสาร Layer 3 จาก route และหลักฐานเส้นทางที่มี', 'ช่วย Network Engineer ตรวจเส้นทางจากต้นทางไปปลายทางแบบ evidence-first โดยแยก route, next hop, asymmetric path และ policy-related hypothesis ออกจากกันก่อนเปลี่ยน config', ['Ping/traffic ไปปลายทางไม่ได้', 'ตรวจ route หรือ next hop ผิดปกติ', 'แยกปัญหา Layer 3 กับ ACL/NAT/upstream'], ['สรุปหลักฐานและเส้นทาง', 'failure domain/hypotheses', 'คำสั่งตรวจต่อและ safe next action'], 'ตัวอย่าง: Source 10.10.50.10 → Destination 10.20.1.20, show ip route มี default route แต่ traceroute หยุดที่ hop 2', { symptoms: 'อธิบายอาการและผลกระทบที่เห็น', source_destination: 'ระบุต้นทาง ปลายทาง และ VRF/VLAN/gateway ถ้ามี', routing_output: 'วาง routing table หรือ show route ที่เกี่ยวข้อง', path_evidence: 'วาง ping, traceroute, ARP หรือ path evidence อื่นที่มี' }),
  CISCO_SWITCH_PORT_TROUBLESHOOTER: meta('ตัววิเคราะห์ปัญหา Port บน Cisco Switch', 'ตรวจ Layer 1/2 ของ switch port จากอาการและ show command โดยไม่เดาว่าสายหรือ port เสียทันที', 'ช่วยไล่ port state, errors, VLAN, STP, PoE และ endpoint/upstream evidence ให้เห็นว่าปัญหาอยู่ชั้นใด', ['Port down/notconnect', 'CRC/drop/duplex issue', 'VLAN/STP/PoE troubleshooting'], ['สถานะ port', 'evidence และ failure domain', 'Cisco commands ที่ควรตรวจต่อ'], 'ตัวอย่าง: Gi1/0/10 connected 100M แต่มี input errors เพิ่ม และผู้ใช้แจ้งหลุดเป็นช่วง ๆ พร้อม show interface/show switchport', { symptoms: 'อธิบายอาการของผู้ใช้หรืออุปกรณ์ที่ต่อ port', show_output: 'วาง show interface, switchport, spanning-tree, power inline หรือ output ที่เกี่ยวข้อง' }),
  WIFI_8021X_NAC_TROUBLESHOOTER: meta('ตัววิเคราะห์ Wi-Fi / 802.1X / NAC', 'ไล่ authentication path ตั้งแต่ client ถึง RADIUS/NAC และ post-auth network access', 'ช่วยแยก association, EAP/certificate, credential, RADIUS, authorization, VLAN และ post-auth connectivity จาก log จริง', ['802.1X login ไม่ผ่าน', 'RADIUS reject/timeout', 'Auth ผ่านแต่เข้า network ไม่ได้'], ['authentication path', 'last known good stage', 'failure domain และ verification steps'], 'ตัวอย่าง: Windows client ต่อ SSID Corp แล้วขึ้น authentication failed; ISE log มี reject code และ WLC log แนบมาด้วย', { symptoms: 'อธิบายอาการและจุดที่ผู้ใช้เห็น error', logs: 'วาง client/WLC/switch/RADIUS/NAC logs ที่มี', environment: 'ระบุ client OS, SSID, auth method, WLC/NAC/RADIUS และ network context' }),
  FIREWALL_ACL_TRAFFIC_ANALYZER: meta('ตัววิเคราะห์ Firewall / ACL Traffic', 'ตรวจ traffic flow เทียบกับ rule/ACL และ log เพื่ออธิบายว่าถูก allow/block ที่จุดใด', 'ช่วย normalize source/destination/protocol/port แล้วตรวจ rule order และ evidence โดยไม่ให้คำแนะนำหลบเลี่ยง security control', ['ACL deny troubleshooting', 'Firewall rule review สำหรับ flow เฉพาะ', 'ตรวจ log เทียบ policy'], ['normalized flow', 'matching rule', 'allow/block reasoning และ safe validation'], 'ตัวอย่าง: 10.1.1.10:ephemeral → 10.2.2.20:443 TCP ถูก deny; แนบ ACL และ firewall log ช่วงเวลาเดียวกัน', { traffic_flow: 'ระบุ source, destination, protocol, port และ direction/zone ถ้ามี', acl_or_rules: 'วาง ACL หรือ policy ตามลำดับจริง', logs: 'วาง deny/allow/session logs ที่เกี่ยวข้อง' }),
  VPN_TROUBLESHOOTER: meta('ตัววิเคราะห์ปัญหา VPN', 'ไล่ปัญหา Site-to-Site หรือ Remote Access VPN ตาม phase ที่เกี่ยวข้อง', 'ช่วยแยก authentication, crypto negotiation, tunnel, routing, NAT, policy, DNS และ application reachability จาก log', ['IPsec tunnel ไม่ขึ้น', 'Remote VPN login ไม่ผ่าน', 'VPN connected แต่เข้าปลายทางไม่ได้'], ['phase-by-phase state', 'failure domain', 'diagnostic steps'], 'ตัวอย่าง: Site-to-Site IPsec IKE SA ขึ้นแต่ไม่มี traffic ผ่าน; แนบ peer logs, route และ NAT evidence', { vpn_type: 'ระบุประเภท VPN และ platform', symptoms: 'อธิบายอาการและผลกระทบ', logs: 'วาง VPN/IKE/auth/routing logs ที่เกี่ยวข้อง' }),
  SECURITY_ALERT_TRIAGE: meta('ตัวคัดกรอง Security Alert', 'คัดกรอง alert จากหลักฐานจริง พร้อม severity factors, containment checks และข้อมูลสำหรับ escalation', 'ช่วย SOC แยก verified facts, suspicious indicators, benign alternatives และ unknowns โดยไม่แต่ง IOC/attribution', ['EDR/SIEM alert', 'Suspicious sign-in', 'Malware/behavioral detection triage'], ['verified facts', 'triage/severity assessment', 'defensive containment และ evidence collection'], 'ตัวอย่าง: EDR แจ้ง PowerShell suspicious behavior บนเครื่อง user 1 เครื่อง พร้อม process tree, timestamp และ hash ที่ระบบให้มา', { alert: 'วาง alert title, entity, rule และรายละเอียดที่ระบบแจ้ง', evidence: 'วาง process/log/IOC/context ที่มีจริง', environment: 'อธิบาย asset role, user privilege และ environment ที่เกี่ยวข้อง' }),
  PHISHING_EMAIL_ANALYZER: meta('ตัววิเคราะห์อีเมล Phishing', 'ตรวจเนื้อหาและ header เพื่อหา phishing/impersonation indicators อย่างปลอดภัย', 'ช่วยวิเคราะห์ sender, reply-to, authentication headers, link/domain patterns และ social engineering โดยไม่สั่งเปิดไฟล์หรือลิงก์ต้องสงสัย', ['ตรวจอีเมลน่าสงสัย', 'วิเคราะห์ impersonation/BEC indicator', 'ตรวจ header ก่อน escalation'], ['risk assessment', 'indicators พร้อม evidence', 'safe defensive next steps'], 'ตัวอย่าง: Display name เป็น CFO แต่ From domain ไม่ใช่บริษัทและขอเปลี่ยนบัญชีรับเงิน พร้อมแนบ Received/SPF/DKIM headers', { email_content: 'วาง subject/body โดยปิดข้อมูลลับที่ไม่จำเป็น', headers: 'วาง email headers เช่น From, Reply-To, Received, SPF/DKIM/DMARC', context: 'ระบุว่าผู้ส่งควรเป็นใครและเหตุการณ์แวดล้อมที่รู้จริง' }),
  CI_CD_PIPELINE_FAILURE_ANALYZER: meta('ตัววิเคราะห์ CI/CD Pipeline ที่ล้มเหลว', 'หา stage แรกที่ผิดจริงจาก log ของ pipeline run เฉพาะครั้ง', 'ช่วยแยก test/build/dependency/config/permission/artifact/deploy failure และสัมพันธ์กับ recent changes โดยไม่สรุป causation เกินหลักฐาน', ['GitHub Actions fail', 'Build/deploy pipeline ล้ม', 'Regression หลัง commit ใหม่'], ['failing stage', 'root-cause candidates', 'minimal verify/fix/rollback direction'], 'ตัวอย่าง: Pipeline test ผ่าน แต่ OpenNext build fail หลังอัปเกรด dependency; แนบ workflow, build log และ diff package version', { pipeline: 'วาง workflow/stage context และ runner/environment', logs: 'วาง log ตั้งแต่ก่อน error แรกจนถึง failure ที่เกี่ยวข้อง', recent_changes: 'สรุป commit/config/dependency changes ล่าสุดที่อาจเกี่ยวข้อง' }),
  PRODUCTION_DEPLOYMENT_READINESS_REVIEWER: meta('ตัวตรวจความพร้อมก่อน Deploy Production', 'ตรวจ test evidence, deployment plan และ rollback plan ก่อน production release', 'ช่วยหา blocking gaps, blast radius, missing success criteria และ rollback risk โดยไม่ถือว่า “build ผ่าน” เท่ากับพร้อม production', ['ก่อน production deploy', 'CAB/release review', 'ตรวจ rollback readiness'], ['readiness status', 'blocking gaps/risks', 'evidence ที่ยังต้องมีสำหรับ go/no-go'], 'ตัวอย่าง: เปลี่ยน payment route; unit/integration tests ผ่าน มี canary plan แต่ rollback ยังไม่ระบุ database compatibility', { change_summary: 'สรุป behavior/components ที่เปลี่ยนและ blast radius ที่ทราบ', test_evidence: 'วางผล tests/build/UAT ที่พิสูจน์ได้', deployment_plan: 'ระบุ steps, prerequisites, monitoring และ success criteria', rollback_plan: 'ระบุ trigger และวิธีย้อนกลับ รวม data/schema compatibility' }),
  RUNTIME_CONFIGURATION_DRIFT_ANALYZER: meta('ตัววิเคราะห์ Configuration Drift', 'เทียบ expected config กับ observed runtime config เพื่อหา drift ที่มีผลจริง', 'ช่วยจำแนก material/cosmetic/environment-specific differences และเชื่อมกับ symptom เฉพาะเมื่อมี causal evidence', ['Environment ทำงานไม่เหมือนกัน', 'Config drift หลัง deploy', 'ตรวจ runtime settings เทียบ baseline'], ['drift summary', 'material differences', 'verification/reconciliation plan'], 'ตัวอย่าง: Production env มี FEATURE_X=true และ API_URL ต่างจาก approved baseline หลัง deploy แล้วเกิด request ไป endpoint ผิด', { expected_config: 'วาง baseline/expected config โดยลบ secrets', observed_config: 'วาง runtime config ที่ตรวจพบจริงโดยลบ secrets', symptoms: 'อธิบาย behavior หรือ incident ที่ต้องการเชื่อมกับ drift' }),
  DATABASE_LOCK_BLOCKING_ANALYZER: meta('ตัววิเคราะห์ Database Lock และ Blocking', 'ไล่ blocker/waiter chain จาก lock/session/transaction evidence', 'ช่วยแยก normal locking, harmful blocking และ deadlock พร้อม safe checks ก่อนพิจารณายุติ session', ['Query ค้างเพราะ lock', 'Transaction blocking chain', 'ตรวจ deadlock/long transaction'], ['blocking chain', 'likely cause', 'safe immediate/long-term remediation'], 'ตัวอย่าง: Session 81 block 92/104 นาน 180s บน orders table; แนบ lock view, transaction age และ query text', { symptoms: 'อธิบาย latency/timeout และผลกระทบ', lock_evidence: 'วาง lock/session/wait evidence จาก DB', transaction_context: 'วาง transaction/query/app context ที่เกี่ยวข้อง' }),
  CSV_EXCEL_DATA_QUALITY_ANALYZER: meta('ตัววิเคราะห์คุณภาพข้อมูล CSV / Excel', 'ตรวจ grain, missingness, duplicates, types, ranges และ join risks จากข้อมูลที่ให้', 'ช่วยตัดสินว่าข้อมูลเหมาะกับเป้าหมายวิเคราะห์หรือไม่ โดยไม่ extrapolate อัตราทั้ง dataset จาก sample เล็ก', ['ตรวจไฟล์ก่อนทำ dashboard', 'หา duplicate/missing/type issue', 'ตรวจ keys และ join readiness'], ['data-quality findings', 'severity/impact', 'checks/cleaning ที่ควรทำต่อ'], 'ตัวอย่าง: ไฟล์ orders 50 ตัวอย่าง มี order_id ซ้ำ, date หลาย format และ customer_id บางแถวว่าง ต้องใช้ทำ revenue dashboard', { data_description: 'อธิบาย dataset, grain, columns และช่วงเวลา', sample_data: 'วาง sample rows หรือสรุป profile ที่มี', goal: 'บอกว่าจะนำข้อมูลไปใช้ตัดสินใจ/วิเคราะห์อะไร' }),
  FUNNEL_DROP_OFF_ANALYZER: meta('ตัววิเคราะห์ Funnel Drop-off', 'หาขั้นตอนที่ conversion ลดลงจาก funnel metrics และ segment data ที่ให้', 'ช่วยคำนวณ/เปรียบเทียบ drop-off จากตัวเลขจริง และแยก causal hypothesis ออกจาก measured movement', ['Signup/checkout funnel', 'Activation drop', 'เปรียบเทียบ conversion ระหว่าง segment'], ['funnel summary', 'largest drop-offs/segments', 'hypotheses และ next analyses'], 'ตัวอย่าง: Visit 10,000 → Signup 2,000 → Verify 1,100 → Activate 700 พร้อม breakdown mobile/desktop และช่วงเวลาเดียวกัน', { funnel_steps: 'วาง step names, counts/rates, date window และ denominator', segment_data: 'วาง breakdown ตาม segment/cohort ที่เทียบกันได้', context: 'อธิบาย release/campaign/known changes โดยไม่สรุปว่าเป็นสาเหตุ' }),
  EVIDENCE_GAP_ASSUMPTION_AUDITOR: meta('ตัวตรวจ Evidence Gap และ Assumption', 'ตรวจ claim/decision ว่าส่วนใดมีหลักฐาน ส่วนใดเป็น assumption และส่วนใดยังพิสูจน์ไม่ได้', 'ช่วยจัดลำดับ evidence gaps ตามผลกระทบต่อการตัดสินใจ และระบุข้อมูลที่ต้องหาเพิ่ม', ['Review proposal', 'ตรวจ executive claim', 'หา assumption ก่อนตัดสินใจ'], ['evidence map', 'unsupported assumptions/conflicts', 'verification priorities'], 'ตัวอย่าง: Decision = ย้ายระบบขึ้น cloud จะลด cost 30%; Evidence มีค่า hardware ปัจจุบันแต่ยังไม่มี cloud usage estimate', { decision_or_claim: 'วางข้อสรุปหรือ decision ที่ต้องการ audit', evidence: 'วางข้อมูล/แหล่ง/ตัวเลขที่มี', criteria: 'ระบุเกณฑ์ที่ใช้ตัดสินว่าหลักฐานเพียงพอหรือไม่' }),
  REQUIREMENTS_TRADE_OFF_ANALYZER: meta('ตัววิเคราะห์ Trade-off ของ Requirements', 'เทียบทางเลือกกับ mandatory/desirable requirements และ constraints อย่างเป็นระบบ', 'ช่วยเห็น requirement conflicts, dependencies และ unknowns โดยไม่สร้างคะแนนหรือ winner เมื่อไม่มี decision rule', ['เลือก tool/vendor', 'ตัดสิน architecture option', 'จัดลำดับ requirement conflicts'], ['requirement matrix', 'trade-offs/conflicts', 'unknowns และ decision implications'], 'ตัวอย่าง: Options = SaaS A/B, Requirements = SSO, audit log, on-prem connector, Budget <= 20k/เดือน และมี evidence จาก vendor docs', { options: 'ระบุแต่ละ option ให้แยกชัด', requirements: 'แยก must-have / nice-to-have ถ้ามี', constraints: 'ระบุ budget/time/platform/compliance constraints', evidence: 'วาง facts/specs ที่ใช้เทียบ option' }),
  INCIDENT_TIMELINE_RECONSTRUCTOR: meta('ตัวสร้าง Incident Timeline จากหลักฐาน', 'รวม logs, alerts และ notes เป็น timeline โดยรักษา timestamp/source/ความไม่แน่นอน', 'ช่วยหา sequence ของ symptom, detection, intervention และ recovery โดยไม่แต่งช่วงเวลาที่ไม่มีหลักฐาน', ['เตรียม postmortem', 'รวม evidence หลายระบบ', 'หาลำดับเหตุการณ์ตอน incident'], ['canonical timeline', 'conflicting/uncertain timestamps', 'timeline gaps และ key transitions'], 'ตัวอย่าง: Syslog 09:02 interface down, monitoring alert 09:03, operator note 09:10 rollback, service recovered 09:14 โดยทุก source ใช้ timezone เดียวกัน', { evidence: 'วาง logs/alerts/chat notes พร้อม timestamp/source ให้มากที่สุด', time_context: 'ระบุ timezone, clock offset หรือข้อจำกัดด้านเวลา ถ้าทราบ' }),
  PROFESSIONAL_MESSAGE_EMAIL_BUILDER: meta('ตัวสร้างข้อความและอีเมลแบบมืออาชีพ', 'เปลี่ยนเป้าหมายและบริบทเป็นข้อความพร้อมส่งโดยไม่แต่งข้อเท็จจริง', 'ช่วยจัด wording, structure และ tone สำหรับงานจริง พร้อมรักษาชื่อ วันที่ ตัวเลข และ commitment ตามข้อมูลผู้ใช้', ['อีเมลแจ้ง incident', 'ติดตามงานกับ vendor', 'ข้อความสุภาพถึงทีม/ลูกค้า'], ['send-ready draft', 'subject suggestion เมื่อเป็น email', 'ไม่มีข้อมูล/คำสัญญาที่แต่งเพิ่ม'], 'ตัวอย่าง: Goal = แจ้ง vendor ว่า circuit ยัง down, Context = Ticket ABC123 เปิด 09:20 และต้องการ ETA, Tone = Professional', { goal: 'บอกว่าต้องการให้ผู้รับทำ/เข้าใจอะไร', context: 'วางข้อเท็จจริง ชื่อ วันที่ ตัวเลข และบริบทที่ใช้เขียน', tone: 'ระบุ tone เช่น Professional, Friendly, Firm but polite' }),
  TRAVEL_RESEARCH_PLANNER: meta('ตัววางแผน Research สำหรับการเดินทาง', 'สร้าง checklist และ framework เพื่อหาข้อมูลที่ต้องยืนยันก่อนจัด itinerary', 'ช่วยแยก preferences/constraints, geographic clusters, transport และข้อมูล current เช่นราคา/เวลาเปิดที่ต้องค้นสด โดยไม่แต่งข้อมูล', ['เริ่มวางทริปใหม่', 'มีเงื่อนไขหลายอย่างต้องจัดลำดับ', 'เตรียมรายการข้อมูลก่อนจอง'], ['trip priorities', 'research checklist', 'itinerary framework และ current facts to verify'], 'ตัวอย่าง: Destination = จันทบุรี, Dates = 10–12 ต.ค., Preferences = ธรรมชาติ+กิจกรรม, Constraints = ขับรถเอง งบที่พัก <=1,500 บาท', { destination: 'ระบุเมือง/จังหวัด/ประเทศหรือพื้นที่หลัก', dates: 'ระบุวันเดินทางหรือช่วงเวลา', preferences: 'บอกประเภทสถานที่ กิจกรรม pace และสิ่งที่ชอบ', constraints: 'ระบุ budget, transport, mobility, opening-time หรือเงื่อนไขสำคัญ' }),
  PUBLIC_COMPANY_RESEARCH_BRIEF: meta('ตัวสร้าง Research Brief บริษัทจดทะเบียน', 'สรุปธุรกิจ/การเงิน/catalysts/risks จากแหล่งข้อมูลที่ผู้ใช้ให้ โดยแยก facts กับ interpretation', 'ช่วยทำ public-equity research แบบ traceable และระบุ stale/conflicting/missing data โดยไม่ออกคำสั่งซื้อขายส่วนบุคคล', ['อ่าน earnings/filing', 'ทำ company brief ก่อนวิเคราะห์ต่อ', 'รวบรวม catalysts/risks จาก sources'], ['business/financial facts', 'evidence-backed catalysts/risks', 'uncertainty และ diligence questions'], 'ตัวอย่าง: Company = CCL, Goal = เข้าใจ earnings drivers 12 เดือน, Sources = 10-Q, earnings transcript และ investor presentation ที่แนบ', { company: 'ระบุชื่อ/ticker และตลาดถ้าจำเป็น', research_goal: 'บอกคำถามที่ต้องการตอบ ไม่ใช่คำสั่ง buy/sell', sources: 'วาง filings/transcript/ข้อมูลที่ต้องการให้ใช้ และวันที่ของแหล่งข้อมูล' }),
  CERTIFICATION_READINESS_GAP_ANALYZER: meta('ตัววิเคราะห์ Gap ก่อนสอบ Certification', 'เทียบหลักฐานความรู้ปัจจุบันกับ exam objectives เพื่อหา topic ที่ยังไม่พิสูจน์ mastery', 'ช่วยจัด priority labs/questions และ study sequence โดยไม่ถือว่า job title หรือ self-rating เท่ากับพร้อมสอบ', ['ประเมินก่อนสอบ CCNA/Network+/Security+', 'หา weak objectives', 'วาง practice ก่อนวันสอบ'], ['readiness map', 'strong/gap areas', 'targeted practice และ checkpoints'], 'ตัวอย่าง: Certification = CCNA, Current evidence = ทำ VLAN/STP lab ได้แต่ OSPF/ACL ยังผิดบ่อย, Exam objectives = official outline, Time = 6 ชม./สัปดาห์', { certification: 'ระบุชื่อ certification/version ถ้าทราบ', current_evidence: 'วางผล mock exam, labs, topics ที่ทำได้/พลาด หรือ evidence อื่น', exam_objectives: 'วาง official objectives หรือรายการหัวข้อที่ใช้เทียบ', time_available: 'ระบุเวลาต่อสัปดาห์และวันสอบ/ระยะเวลาที่เหลือ' }),
});
