export const CONTENT_PROMPTS = [
  {
    name: "BLOG_GENERATOR",
    displayTitle: "Blog Generator",
    description: "Generate structured long-form blog content.",
    category: "Writing",
    prompt: "Write a high-quality blog post.\n\nTopic:\n\n{{topic}}\n\nAudience:\n\n{{audience}}\n\nTone:\n\n{{tone}}\n\nTarget length:\n\n{{length}}\n\nStructure:\n\n- Title\n- Introduction\n- Key sections\n- Examples\n- Practical advice\n- Conclusion\n\nAvoid unnecessary repetition and generic filler.",
    variables: ["topic", "audience", "tone", "length"],
    tags: ["BLOG", "WRITING", "CONTENT"],
    collections: ["AI Prompt Library", "Content Creator", "Popular AI Prompts"],
    outputFormat: "Long-form blog article",
  },
  {
    name: "SEO_CONTENT_WRITER",
    displayTitle: "SEO Content Writer",
    description: "Generate SEO-focused articles, metadata, structure, and FAQs.",
    category: "Marketing",
    prompt: "Create an SEO-focused article.\n\nTopic:\n\n{{topic}}\n\nPrimary keyword:\n\n{{primary_keyword}}\n\nSecondary keywords:\n\n{{secondary_keywords}}\n\nAudience:\n\n{{audience}}\n\nGenerate:\n\nSEO title:\nMeta description:\nSuggested URL slug:\nH1:\nH2/H3 structure:\nArticle:\nFAQ section:\nInternal-link suggestions:\n\nUse keywords naturally.\n\nAvoid keyword stuffing.",
    variables: ["topic", "primary_keyword", "secondary_keywords", "audience"],
    tags: ["SEO", "CONTENT", "MARKETING"],
    collections: ["AI Prompt Library", "Content Creator"],
    outputFormat: "SEO article package with metadata, structure, FAQ, and links",
  },
  {
    name: "SOCIAL_CONTENT_GENERATOR",
    displayTitle: "Social Content Generator",
    description: "Generate social media content for different platforms and audiences.",
    category: "Marketing",
    prompt: "Create {{count}} social media posts.\n\nTopic:\n\n{{topic}}\n\nPlatform:\n\n{{platform}}\n\nAudience:\n\n{{audience}}\n\nTone:\n\n{{tone}}\n\nEach post should include:\n\n- Hook\n- Main content\n- Call to action\n\nGenerate different creative angles.\n\nAvoid repeating the same concept.",
    variables: ["count", "topic", "platform", "audience", "tone"],
    tags: ["SOCIAL", "CONTENT", "MARKETING"],
    collections: ["AI Prompt Library", "Content Creator"],
    outputFormat: "Multiple social media posts",
  }
];
