export const DATA_PROMPTS = [
  {
    name: "JSON_EXTRACTOR",
    displayTitle: "JSON Data Extractor",
    description: "Extract structured information and return valid JSON.",
    category: "Data",
    prompt: "Extract structured information from:\n\n{{content}}\n\nReturn valid JSON only.\n\nRequired schema:\n\n{{schema}}\n\nRules:\n\n- Do not invent missing information.\n- Use null when a value cannot be determined.\n- Preserve names, dates, and numbers accurately.\n- Follow the supplied schema exactly.\n- Return valid JSON only.",
    variables: ["content", "schema"],
    tags: ["JSON", "EXTRACTION", "DATA"],
    collections: ["AI Prompt Library", "Data & Analysis", "Popular AI Prompts"],
    outputFormat: "Valid JSON only",
  },
  {
    name: "TABLE_EXTRACTOR",
    displayTitle: "Table Data Extractor",
    description: "Convert unstructured content into structured tables.",
    category: "Data",
    prompt: "Extract the important structured information from:\n\n{{content}}\n\nReturn a table using these columns:\n\n{{columns}}\n\nRules:\n\n- One entity per row\n- Preserve original values\n- Use N/A for missing information\n- Remove duplicate records\n- Do not guess missing values",
    variables: ["content", "columns"],
    tags: ["TABLE", "DATA", "EXTRACTION"],
    collections: ["AI Prompt Library", "Data & Analysis"],
    outputFormat: "Table",
  },
  {
    name: "SENTIMENT_ANALYZER",
    displayTitle: "Sentiment Analyzer",
    description: "Analyze sentiment, emotion, intent, and urgency from text.",
    category: "Data",
    prompt: "Analyze the sentiment of:\n\n{{text}}\n\nReturn:\n\nOverall sentiment:\nPositive score:\nNeutral score:\nNegative score:\n\nKey emotional signals:\nImportant phrases:\nPossible sarcasm:\nCustomer intent:\nUrgency level:\n\nExplain the classification briefly.",
    variables: ["text"],
    tags: ["SENTIMENT", "NLP", "ANALYSIS"],
    collections: ["AI Prompt Library", "Data & Analysis"],
    outputFormat: "Structured sentiment analysis",
  },
  {
    name: "DATA_CLASSIFIER",
    displayTitle: "AI Data Classifier",
    description: "Classify content into predefined categories and return structured JSON.",
    category: "Data",
    prompt: "Classify the following input:\n\n{{input}}\n\nAvailable categories:\n\n{{categories}}\n\nReturn valid JSON:\n\n{\n  \"category\": \"\",\n  \"confidence\": 0,\n  \"reason\": \"\",\n  \"alternative_category\": \"\"\n}\n\nUse only the provided categories.\n\nDo not create new categories.",
    variables: ["input", "categories"],
    tags: ["CLASSIFICATION", "DATA", "JSON"],
    collections: ["AI Prompt Library", "Data & Analysis"],
    outputFormat: "Valid JSON only",
  }
];
