export const DEVELOPMENT_PROMPTS = [
  {
    name: "CODE_REVIEWER",
    displayTitle: "Professional Code Reviewer",
    description: "Review source code for bugs, security risks, performance, architecture, and maintainability.",
    category: "Coding",
    prompt: "Perform a professional code review.\n\nLanguage / Framework:\n\n{{technology}}\n\nCode:\n\n{{code}}\n\nAnalyze:\n\n- Bugs\n- Logic problems\n- Security risks\n- Performance issues\n- Maintainability\n- Readability\n- Error handling\n- Edge cases\n- Architecture problems\n\nFor every issue provide:\n\nSeverity:\nLocation:\nProblem:\nWhy it matters:\nRecommended fix:\n\nThen provide an improved version of the code.",
    variables: ["technology", "code"],
    tags: ["CODE", "REVIEW", "DEBUG", "SECURITY"],
    collections: ["AI Prompt Library", "Developer Toolkit", "Popular AI Prompts"],
    outputFormat: "Issue-by-issue code review plus improved code",
  },
  {
    name: "BUG_HUNTER",
    displayTitle: "Bug Hunter",
    description: "Diagnose software bugs and identify their root causes.",
    category: "Coding",
    prompt: "Debug the following problem.\n\nExpected behavior:\n\n{{expected_behavior}}\n\nActual behavior:\n\n{{actual_behavior}}\n\nError:\n\n{{error}}\n\nCode:\n\n{{code}}\n\nDetermine:\n\n1. Most likely root cause\n2. Other possible causes\n3. How to reproduce the problem\n4. Diagnostic steps\n5. Exact fix\n6. How to verify the fix\n7. How to prevent regression",
    variables: ["expected_behavior", "actual_behavior", "error", "code"],
    tags: ["BUG", "DEBUG", "TROUBLESHOOTING"],
    collections: ["AI Prompt Library", "Developer Toolkit", "Popular AI Prompts"],
    outputFormat: "Root-cause diagnostic report",
  },
  {
    name: "UNIT_TEST_GENERATOR",
    displayTitle: "Unit Test Generator",
    description: "Generate comprehensive unit tests including normal cases, edge cases, failures, and regressions.",
    category: "Coding",
    prompt: "Generate comprehensive unit tests for:\n\n{{code}}\n\nTesting framework:\n\n{{test_framework}}\n\nInclude tests for:\n\n- Normal cases\n- Edge cases\n- Invalid input\n- Empty input\n- Boundary conditions\n- Expected failures\n- Regression scenarios\n\nExplain what each test validates.",
    variables: ["code", "test_framework"],
    tags: ["TEST", "UNIT_TEST", "CODE"],
    collections: ["AI Prompt Library", "Developer Toolkit"],
    outputFormat: "Unit test suite with explanations",
  },
  {
    name: "CODE_OPTIMIZER",
    displayTitle: "Code Optimizer",
    description: "Optimize source code for performance, efficiency, and maintainability.",
    category: "Coding",
    prompt: "Analyze and optimize the following code:\n\n{{code}}\n\nOptimization goal:\n\n{{optimization_goal}}\n\nEvaluate:\n\n- Execution speed\n- Memory usage\n- Algorithm efficiency\n- Duplicate operations\n- Network requests\n- Database queries\n- Maintainability\n\nExplain each optimization before providing the improved code.",
    variables: ["code", "optimization_goal"],
    tags: ["OPTIMIZATION", "PERFORMANCE", "CODE"],
    collections: ["AI Prompt Library", "Developer Toolkit"],
    outputFormat: "Optimization report plus improved code",
  },
  {
    name: "TIME_COMPLEXITY_ANALYZER",
    displayTitle: "Time Complexity Analyzer",
    description: "Analyze Big-O time and space complexity.",
    category: "Coding",
    prompt: "Analyze the computational complexity of this code:\n\n{{code}}\n\nReturn:\n\nTime Complexity:\nSpace Complexity:\nBest Case:\nAverage Case:\nWorst Case:\n\nIdentify the operations responsible for the complexity.\n\nThen suggest a more efficient algorithm if possible.",
    variables: ["code"],
    tags: ["BIG_O", "ALGORITHM", "PERFORMANCE"],
    collections: ["AI Prompt Library", "Developer Toolkit"],
    outputFormat: "Big-O complexity report",
  },
  {
    name: "REGEX_GENERATOR",
    displayTitle: "Regex Generator",
    description: "Convert natural-language requirements into regular expressions.",
    category: "Coding",
    prompt: "Convert the following requirement into a regular expression:\n\n{{requirement}}\n\nTarget language:\n\n{{language}}\n\nReturn:\n\nRegex:\nExplanation:\nValid examples:\nInvalid examples:\nEdge cases:\nEscaped version for {{language}}:\n\nAvoid overly broad matching.",
    variables: ["requirement", "language"],
    tags: ["REGEX", "VALIDATION", "CODE"],
    collections: ["AI Prompt Library", "Developer Toolkit"],
    outputFormat: "Regex, explanation, examples, and escaped form",
  },
  {
    name: "DOCKER_GENERATOR",
    displayTitle: "Docker Generator",
    description: "Generate a production-ready Docker setup.",
    category: "DevOps",
    prompt: "Create a production-ready Docker setup.\n\nApplication:\n\n{{application}}\n\nTechnology:\n\n{{technology}}\n\nRequirements:\n\n{{requirements}}\n\nGenerate:\n\n- Dockerfile\n- .dockerignore\n- docker-compose.yml if required\n- Environment variable configuration\n- Health check\n- Build command\n- Run command\n\nOptimize the image for:\n\n- Security\n- Build caching\n- Image size\n- Production reliability",
    variables: ["application", "technology", "requirements"],
    tags: ["DOCKER", "DEVOPS", "DEPLOYMENT"],
    collections: ["AI Prompt Library", "Developer Toolkit"],
    outputFormat: "Dockerfile / .dockerignore / compose / environment and run instructions",
  },
  {
    name: "API_DESIGNER",
    displayTitle: "REST API Designer",
    description: "Design production-ready REST APIs.",
    category: "Coding",
    prompt: "Design a REST API for:\n\n{{application}}\n\nRequirements:\n\n{{requirements}}\n\nProvide:\n\nResources:\nEndpoints:\nHTTP methods:\nRequest schemas:\nResponse schemas:\nAuthentication:\nAuthorization:\nValidation:\nError responses:\nRate limiting:\nPagination:\nVersioning:\n\nInclude example requests and responses.",
    variables: ["application", "requirements"],
    tags: ["API", "REST", "BACKEND"],
    collections: ["AI Prompt Library", "Developer Toolkit"],
    outputFormat: "REST API specification with example requests and responses",
  },
  {
    name: "DATABASE_SCHEMA_DESIGNER",
    displayTitle: "Database Schema Designer",
    description: "Design relational database schemas and SQL tables.",
    category: "Database",
    prompt: "Design a database schema for:\n\n{{system}}\n\nRequirements:\n\n{{requirements}}\n\nGenerate:\n\nEntities:\nTables:\nColumns:\nData types:\nPrimary keys:\nForeign keys:\nRelationships:\nIndexes:\nConstraints:\n\nExplain normalization and indexing decisions.\n\nAlso provide SQL CREATE TABLE statements.",
    variables: ["system", "requirements"],
    tags: ["DATABASE", "SQL", "SCHEMA"],
    collections: ["AI Prompt Library", "Developer Toolkit", "Data & Analysis"],
    outputFormat: "Relational schema design plus SQL CREATE TABLE statements",
  }
];
