export const MULTIMODAL_PROMPTS = [
  {
    name: "IMAGE_OBJECT_ANALYZER",
    displayTitle: "Image Object Analyzer",
    description: "Analyze objects, environments, text, and important details in images.",
    category: "Vision",
    prompt: "Analyze the provided image.\n\nIdentify:\n\n- Main objects\n- People\n- Environment\n- Visible text\n- Colors\n- Materials\n- Possible object functions\n- Important visual details\n\nClearly separate direct observations from uncertain interpretations.",
    variables: [],
    tags: ["IMAGE", "VISION", "OBJECT"],
    collections: ["AI Prompt Library", "Multimodal AI", "Popular AI Prompts"],
    outputFormat: "Structured visual analysis",
  },
  {
    name: "IMAGE_TO_JSON",
    displayTitle: "Image to JSON",
    description: "Extract structured information from an image and return JSON.",
    category: "Vision",
    prompt: "Analyze the provided image.\n\nExtract information using this schema:\n\n{{schema}}\n\nReturn valid JSON only.\n\nRules:\n\n- Do not invent information.\n- Use null when information cannot be identified.\n- Preserve visible text accurately.\n- Follow the schema exactly.",
    variables: ["schema"],
    tags: ["IMAGE", "JSON", "EXTRACTION"],
    collections: ["AI Prompt Library", "Multimodal AI"],
    outputFormat: "Valid JSON only",
  },
  {
    name: "VIDEO_QA",
    displayTitle: "Video Q&A",
    description: "Analyze a video and answer questions with timestamp-based evidence.",
    category: "Video",
    prompt: "Analyze the provided video.\n\nQuestion:\n\n{{question}}\n\nAnswer using evidence from the video.\n\nReturn:\n\nAnswer:\nRelevant timestamp:\nObserved evidence:\nConfidence:\nUncertain details:\n\nClearly separate observations from interpretation.",
    variables: ["question"],
    tags: ["VIDEO", "QA", "MULTIMODAL"],
    collections: ["AI Prompt Library", "Multimodal AI"],
    outputFormat: "Answer with timestamp-based evidence",
  },
  {
    name: "AUDIO_TRANSCRIBER",
    displayTitle: "Audio Transcriber",
    description: "Transcribe audio with speaker separation and timestamps.",
    category: "Audio",
    prompt: "Transcribe the provided audio.\n\nRequirements:\n\n- Separate speakers\n- Add timestamps\n- Preserve important terminology\n- Identify unclear sections\n- Do not guess inaudible words\n\nFormat:\n\n[00:00] Speaker 1:\n...\n\n[00:10] Speaker 2:\n...",
    variables: [],
    tags: ["AUDIO", "TRANSCRIPTION", "DIARIZATION"],
    collections: ["AI Prompt Library", "Multimodal AI"],
    outputFormat: "Timestamped speaker-separated transcript",
  }
];
