export const RESEARCH_PROMPTS = [
  {
    name: "DEEP_RESEARCH_ASSISTANT",
    displayTitle: "Deep Research Assistant",
    description: "Research a topic systematically with evidence, competing viewpoints, limitations, and uncertainty.",
    category: "Research",
    prompt: "Act as a professional research assistant.\n\nResearch the following topic:\n\n{{topic}}\n\nResearch objectives:\n\n{{objectives}}\n\nAnalyze:\n\n- Key facts\n- Important concepts\n- Recent developments\n- Major arguments\n- Supporting evidence\n- Conflicting viewpoints\n- Risks\n- Limitations\n- Open questions\n\nClearly distinguish between:\n\n1. Verified facts\n2. Expert interpretations\n3. Uncertain or disputed information\n\nProvide a concise conclusion and list the most important sources that should be verified.",
    variables: ["topic", "objectives"],
    tags: ["RESEARCH", "ANALYSIS", "SOURCES", "DEEP_RESEARCH"],
    collections: ["AI Prompt Library", "Research Toolkit", "Popular AI Prompts"],
    outputFormat: "Structured research report with evidence, uncertainty, conclusion, and sources to verify",
  },
  {
    name: "FACT_CHECKER",
    displayTitle: "AI Fact Checker",
    description: "Analyze claims, evidence, missing context, and uncertainty.",
    category: "Research",
    prompt: "Analyze the following claim:\n\n{{claim}}\n\nPerform a fact-check.\n\nReturn:\n\nClaim:\nVerdict:\nEvidence:\nSupporting evidence:\nContradicting evidence:\nMissing context:\nConfidence level:\nSources to verify:\n\nDo not treat unsupported claims as facts.\n\nClearly indicate uncertainty.",
    variables: ["claim"],
    tags: ["FACT_CHECK", "VERIFY", "RESEARCH"],
    collections: ["AI Prompt Library", "Research Toolkit", "Popular AI Prompts"],
    outputFormat: "Structured fact-check report",
  },
  {
    name: "ARTICLE_ANALYZER",
    displayTitle: "Article Analyzer",
    description: "Analyze the arguments, evidence, assumptions, bias, and missing information in an article.",
    category: "Research",
    prompt: "Analyze the following article:\n\n{{article}}\n\nReturn:\n\n1. Main argument\n2. Key points\n3. Supporting evidence\n4. Assumptions\n5. Potential bias\n6. Weak arguments\n7. Missing information\n8. Important claims\n9. Questions that should be investigated\n10. Concise summary",
    variables: ["article"],
    tags: ["ARTICLE", "ANALYSIS", "RESEARCH"],
    collections: ["AI Prompt Library", "Research Toolkit"],
    outputFormat: "Numbered article analysis",
  },
  {
    name: "PAPER_ANALYZER",
    displayTitle: "Research Paper Analyzer",
    description: "Analyze academic papers, methodology, data, findings, and limitations.",
    category: "Research",
    prompt: "Analyze the following research paper:\n\n{{paper}}\n\nExtract:\n\nResearch question:\nHypothesis:\nMethodology:\nDataset:\nSample size:\nVariables:\nKey findings:\nStatistical methods:\nLimitations:\nPotential biases:\nAuthors' conclusion:\nPractical implications:\n\nFinally explain the paper in simple language for a non-expert.",
    variables: ["paper"],
    tags: ["PAPER", "ACADEMIC", "RESEARCH"],
    collections: ["AI Prompt Library", "Research Toolkit"],
    outputFormat: "Structured academic paper analysis plus plain-language explanation",
  },
  {
    name: "SOURCE_COMPARATOR",
    displayTitle: "Source Comparator",
    description: "Compare multiple information sources and identify agreements, disagreements, and reliability indicators.",
    category: "Research",
    prompt: "Compare the following sources about:\n\n{{topic}}\n\nSources:\n\n{{sources}}\n\nCreate a comparison showing:\n\n- Main claim\n- Evidence\n- Areas of agreement\n- Areas of disagreement\n- Missing information\n- Reliability indicators\n- Publication date\n- Possible bias\n\nDo not assume that multiple sources repeating the same claim automatically proves it.",
    variables: ["topic", "sources"],
    tags: ["SOURCE", "COMPARE", "VERIFY", "RESEARCH"],
    collections: ["AI Prompt Library", "Research Toolkit"],
    outputFormat: "Source comparison table/report",
  }
];
